### ISSUE TITLE
Launcher Controller Not Working

### ISSUE THREAD

**Issue by jobensingh** [BuiltBrokenModding/ICBM#100]
Hi, Whenever I open a launcher controller i get this
![2015-06-06_15 29 31](https://cloud.githubusercontent.com/assets/12707917/8021976/54c1a1bc-0c6b-11e5-95fd-378b703df7ac.png)

**Comment by jobensingh** [comment]
Also A while ago after messing around with a data chip I managed to get it to this screen but I still cant input coords.
![2015-06-06_15 29 31](https://cloud.githubusercontent.com/assets/12707917/8021981/9154215e-0c6b-11e5-86fe-812d801e0eba.png)

**Comment by jobensingh** [comment]
It also causes the same problem as i posted in the portable launcher issue

**Comment by DarkGuardsman** [comment]
Make sure your using the lastest and click launcher # button to input coords.

**Comment by jobensingh** [comment]
There is no option to input the coords 
![2015-06-07_13 53 51](https://cloud.githubusercontent.com/assets/12707917/8026014/aa086f0a-0d1c-11e5-976c-ad3a2bdb2333.png)

**Comment by DarkGuardsman** [comment]
Odd... make sure you using the latest version from here http://www.builtbroken.com/pages/icbm/1.7/downloads.php

**Comment by jobensingh** [comment]
Iv been told to make sure about that many many many many! times and I have but this problem still persists I just really want this mod

**Comment by jobensingh** [comment]
Whats The Problem?!?

**Comment by jobensingh** [comment]
Do i need to download the developer or something?

**Comment by dmodoomsirius** [comment]
No from that site you need the ICBM-<version>-dev.jar not the -dev-deobf.jar otherwise mc will crash with an exception for sure. Dark will get to adding more content soon. He is busy with other mods and things. I have been busy with voltz and other things as well. The rewrite was because it was over due anyway.

**Comment by jobensingh** [comment]
Ok Thanks for the help I hope you guys can fix it soon
