### ISSUE TITLE
Mod Won't Launch (Server Side) 

### ISSUE THREAD

**Issue by AutoJukebox** [BuiltBrokenModding/ICBM#102]
So installed the latest version of ICBM and VoltzEngine from http://builtbroken.com/ and my server doesn't seem to launch anymore....

Crash Report: http://pastebin.com/Pw2VvvUX

It could be a mod conflict but i figured i'd come here first before i go deleting mods....

Thanks.

**Comment by dmodoomsirius** [comment]
You grabbed the Deobf version ICBM-1.7.10-2.4.0b259-deobf-dev.jar not the -dev.jar verision. This is the one you need is [here.](http://adf.ly/2380428/ci.builtbroken.com/maven/dev/builtbroken/icbm/ICBM/1.7.10-2.4.0b259/ICBM-1.7.10-2.4.0b259-dev.jar)

**Comment by AutoJukebox** [comment]
Tried that, came back with the same crash.

**Comment by dmodoomsirius** [comment]
What is the exact name of both ICBM and VoltzEngine jar files?

**Comment by AutoJukebox** [comment]
Nevermind. I updated my voltzengine (which i thought i had done) now it works. So sorry for the trouble :/

**Comment by dmodoomsirius** [comment]
No trouble at all.
