### ISSUE TITLE
Proper installation instructions

### ISSUE THREAD

**Issue by Tankernn** [BuiltBrokenModding/ICBM#103]
The instructions in README.md do not include installing Resonant Engine, which is asked for when launching Minecraft.

**Comment by Tankernn** [comment]
Oops, I thought the curse download was actually updated, sorry.

**Comment by Hennamann** [comment]
Resonant Engine is only needed when running pre 1.7.10 versions of ICBM.

**Comment by dmodoomsirius** [comment]
Curseforge downloads are updated they are marked as alpha so they won't show up on curse.com. When dark and I are ready we will change it to beta and it will show on curse.

**Comment by Tankernn** [comment]
Thank you, I realized this just after I posted the issue. I'm sorry for wasting your time on my derpyness.
Den 4 aug 2015 1:11 em skrev dmodoomsirius <notifications@github.com>:Curseforge downloads are updated they are marked as alpha so they won't show up on curse.com. When dark and I are ready we will change it to beta and it will show on curse.
