### ISSUE TITLE
Technic Permissions

### ISSUE THREAD

**Issue by GeARCraft1** [BuiltBrokenModding/ICBM#105]
Hi!
I need permissions to use this mod at my new modpack, TechPack1. Can you give-me please?
Thank you and have a good night,
GeARCraft1

**Comment by GreenCafe** [comment]
Can we have a link to the modpack?

What's the modpack about?

**Comment by GeARCraft1** [comment]
I m setting up the mod pack on solder. The mod pack will be something about technology and adventure, coming with a lot of maps.

**Comment by dmodoomsirius** [comment]
http://builtbroken.com/pages/modpack.php

**Comment by GreenCafe** [comment]
What is the Solid core theme that doesn't change for the pack?

**Comment by DarkGuardsman** [comment]
For the moment I'm going to say no as the mod is too unstable. Re-open this later once the mod is stabilized and we can talk about your plans for using the mod.
