### ISSUE TITLE
Technic Permissions

### ISSUE THREAD

**Issue by GeARCraft1** [BuiltBrokenModding/ICBM#106]
Hi!! I'm here again to ask for permission to use this mod in my modpack! It was been released on Beta and definitely it isn't a "kitchen-soup modpack". Link: http://www.technicpack.net/modpack/techadventuretp1.718441
Ah, and there is much more to come in this modpack. Currently, i'm working in a custom initialization vídeo. The modpack run's on Solder.

**Comment by GeARCraft1** [comment]
Ah, and there is much more to come in this modpack. Currently, i'm working in a custom initialization vídeo.

**Comment by DarkGuardsman** [comment]
Its not kitchen soup but I still need to know what you plan to use the mod for inside the pack. As your not a warfare pack and ICBM is not exactly designed for PvE.

**Comment by GeARCraft1** [comment]
Well, I Plan to use ICBM um some Maps and warfare servers.
