### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by FlackJacketJoe** [BuiltBrokenModding/ICBM#107]
So I've been trying to download the update to the latest ICBM 2.4.0-264 and i keep getting the same error after i get through ad.fly saying "the web page is not available" giving the error "DNS_PROBE_FINISHED_NXDOMAIN" i get that error on chrome and Firefox basically says the same. I've run out of Ideas and wondering if it is something on your end. any help would be appreciated thanks

**Comment by dmodoomsirius** [comment]
I am in the process of changing build servers so the downloads page hasn't been run in a while 
http://ci.dmodoomsirius.me/maven/dev/builtbroken/icbm/ICBM/1.7.10-2.4.0b264/ICBM-1.7.10-2.4.0b264-dev.jar here you go

**Comment by FlackJacketJoe** [comment]
thanks for the link. It's a really good mod looking forward to the finished product

**Comment by dmodoomsirius** [comment]
I am working on documentation for that on http://docs.dmodoomsirius.me/docs under maven. working on the page now to download dev builds of icbm.
