### ISSUE TITLE
Permission for pack

### ISSUE THREAD

**Issue by GrandHunterMan** [BuiltBrokenModding/ICBM#109]
Hi, just asking for permission to use this mod in a pack. It's an advanced themed techpack with HQM to help people learn the mods.

**Comment by dmodoomsirius** [comment]
Please follow http://builtbroken.net/pages/modpack.php

**Comment by DarkGuardsman** [comment]
Hmm, how exactly do you plan to help people learn ICBM? If you can layout your plan most likely I'll give you permission.

**Comment by GrandHunterMan** [comment]
I am following the guide, I have everything ready except the actual permission. 

As for teaching people ICBM, I plan on adding several quests on setting up the infrastructure and preforming an initial missile strike. None of this is exact, just what I plan.

     Craft launching station + missile crafter(Other pre-requisites will already be taken care of)
     Craft basic missile.
     Ready launcher(Cords) + Launch missile

**Comment by DarkGuardsman** [comment]
Cool, I should be able to give you permission for ICBM then. First though I need a URL link to the pack so I can place it on this list https://docs.google.com/spreadsheets/d/13SXh1AeaJx07Tt4MXCg-Kz5mNxXLI-ilShrIZlSC8E8/edit?usp=sharing

**Comment by GrandHunterMan** [comment]
The pack is still in development. I'll let you know when it's published.
