### ISSUE TITLE
Crash when rightclicking a missile on a station with a Data Module

### ISSUE THREAD

**Issue by MyNameIsKodos** [BuiltBrokenModding/ICBM#115]
http://puu.sh/l4Jco/3c7f2c8ef1.txt

**Comment by dmodoomsirius** [comment]
Changed to be the pastebin not the report so its not a giant wall of text.

**Comment by DarkGuardsman** [comment]
Looks simple should have it fixed shortly

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/commit/88e0459413e40a2a71fb73fdadbd1f5de16ba13f
