### ISSUE TITLE
Small missle casing

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/ICBM#119]
Small missile casing is being rejected by the missile work station. when i try to put the small missile casing in the missile work station it says "I don't think that goes into here."

**Comment by DarkGuardsman** [comment]
Doesn't seem to be an issue when testing in the dev workspace. You sure it was a small missile and not a micro missile. As the crafting station can only support the small missiles at the moment.

**Comment by dmodoomsirius** [comment]
retested might have been the small micro missile.
