### ISSUE TITLE
[Suggestion] Rocketfire should set things ablaze

### ISSUE THREAD

**Issue by Nakopa** [BuiltBrokenModding/ICBM#122]
(Mostly the fact that a rocket can start in a treehouse irritates me) I think its needed since you guys already started to implement some reality (shrapnells etc) to the mod. Stuff like grassblocks become dirt when exposed to the exhaustion-fire of a rocket and entites should become ablazed

**Comment by DarkGuardsman** [comment]
Sound reasonable as I've already implemented chances that the missile can explode in the silo. It wouldn't be too hard for the exhaust to cause fires. Though it will have to wait until I can create upgrades for the silo. This way users can incase the silo to prevent fires to gear nearby.

**Comment by DarkGuardsman** [comment]
Partially completed https://github.com/BuiltBrokenModding/ICBM/commit/8633e973b2763bc81150785b5cb4e1debb6de6f8
