### ISSUE TITLE
[Suggestion] A simple defence system included, at least

### ISSUE THREAD

**Issue by Anghelos92** [BuiltBrokenModding/ICBM#127]
I Think that if this mod will be out without a defence system to destroy incoming missiles it will be useless because no one will use a destructive mod in a server without the possibility to defende themself. I think a simple defence system like a rf powered laser that shoot incoming missiles will be ok, without radars or something complicated like that you, as you said, will add in an other mod. Is THAT mod already in development? It's a shame that this mod ended in this way after the glorious days of 1.5.2 and 1.6.4

**Comment by dmodoomsirius** [comment]
Yes it is still in development we have builds that can be downloaded off our site or curse.

**Comment by DarkGuardsman** [comment]
Several ways to shoot down missiles are planned but we are still early into development. Currently plan is to finish the missiles. Then to move onto power systems, and some mod intergration. After this radar will be implemented which will connected to AA systems.

**Comment by Anghelos92** [comment]
Thank you For Your replies, I am really happy to Know that. Am I Too rude asking For an estimated time of release of the defence System? Sorry For this question but Your mod is one of the reason I am still playing minecraft. Thank you For your work and keep going! :)

**Comment by DarkGuardsman** [comment]
Normal answer is soon, which means when ever it gets released. That being said I would expect at least a month. Especially considering the list of stuff to complete before hand. Who knows though maybe it will get completed sooner or much latter than expected.

**Comment by robthegray** [comment]
if you had MCHeli you could probably shoot down incoming missiles with the AA weapons

**Comment by Anghelos92** [comment]
Interesting...but I will wait for a solution integrated in your mods, because I prefer automatic defence systems :) . Thank you for your suggestion and keep your work, I really need your mod :)

**Comment by DarkGuardsman** [comment]
That is if MCHeli AA weapons can target the missiles as they are not EntityLiving. Meaning they may look like MC carts to any automated weapons. Though there is an API the MCHeli can implement to correct this without any problems.

Also I'm going to try to implement an Anti-Missile missile in the next two weeks. It will not be automated so you may need to use redstone or OpenComputers to control it.

**Comment by Anghelos92** [comment]
Very well, thank you for your answers and for sharing this informations about the development state of this mod. I wish you good luck...with your work you make happy a lot of minecraft players, thank you again.

**Comment by DaMachinator** [comment]
I think MCHeli AA weapon turrets can be player controlled.
I know the PHALANX CIWS style gatling and missile turrets can be. 
@Anghelos92 How did you get MCHeli to work? It always crashes for me.

**Comment by Anghelos92** [comment]
I did non try that mod, i am waiting For the defence System that Will be integrated by the mod authors of ICBM. Sorry I can't be  helpful here!

**Comment by wormzjl** [comment]
Also suggesting some kind of creative defense system that will neutralize all missles in a given radius

**Comment by DaMachinator** [comment]
Do missiles ignore spawn protection?

**Comment by DarkGuardsman** [comment]
At the moment no, still working on the built in world guard style protection system. Which will automatically protect spawn from missiles when done.

**Comment by DaMachinator** [comment]
I'll make my own AA turret mod, then...

Shoot down missiles with magical laser beams!

**Comment by DarkGuardsman** [comment]
:) Love to see it when your done

**Comment by DaMachinator** [comment]
I was kidding

**Comment by DarkGuardsman** [comment]
Ok so a basic AMS, anti-missile system, turret has been implemented. Should be released in the next  few builds and only contains basic functionality. I will be adding an Anti-missile missile down the road and more turrets as I go. However, additional turrets may end up in another mod. Which was the original plan rather than adding a turret to ICBM.

**Comment by DaMachinator** [comment]
Hmmm....seems like i should update....

Does ICBM need any of the extra ores added by VoltzEngine, or can I disable those

**Comment by DarkGuardsman** [comment]
Most likely useless you have a mod that offers the same ores. As everything is ore dictionary supported so metals from IC2, and TE should work. As well if disabled the recipes may default to vanilla items but is not guaranteed.
