### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DaMachinator** [BuiltBrokenModding/ICBM#129]
Game inexplicably crashes during startup.
http://paste.ee/p/iua5R

**Comment by DarkGuardsman** [comment]
Looks like the access transformers failed in voltz engine. This is a known issue we have been working to correct.

**Comment by dmodoomsirius** [comment]
please try http://adf.ly/2380428/api.dmodoomsirius.me/dev/builtbroken/voltzengine/VoltzEngine/1.7.10-0.8.0b215/VoltzEngine-1.7.10-0.8.0b215-dev-universal.jar should work now. let me know if it is still failing.

**Comment by DaMachinator** [comment]
Game started.
