### ISSUE TITLE
Crashing on startup - possible 404 error.

### ISSUE THREAD

**Issue by Flenix** [BuiltBrokenModding/ICBM#132]
Getting this crash when trying to run ICBM. Only mods instaleld are ICBM & Voltz. I think it's getting a 404 when trying to download CodingLib, but I've manually added that (and also tried MinecraftJUnit) to no avail

http://pastebin.com/hbfYpc7X

Surprised there's no other reports though - maybe I'm just doing something wrong?

**Comment by Hennamann** [comment]
You're running the dev version of Voltz Engine, make sure to download the normal version and not the dev version or things won't work.

**Comment by dmodoomsirius** [comment]
That is the obfuscated version of icbm. If it said -dev-deobf it would be the deobf version. I'll look into it when I can.

**Comment by Hennamann** [comment]
Oh whoops, i should't be reading or answering crash reports when i'm sleepy...

**Comment by Flenix** [comment]
Dmod notified me via IRC that this is fixed and I can confirm it is, so I'll close it for ya'll :)
