### ISSUE TITLE
Galacticraft Support

### ISSUE THREAD

**Issue by jeg623** [BuiltBrokenModding/ICBM#133]
Launching missiles is great. But what if you could launch them from Mars or the moon? Trust me this would be pretty nostalgic.  Imagine artillery (doesn't have to be artillery) raining down on your enemies form the safety of you moon base and launching missiles at another enemy. I understand that it would be a massive undertaking since most of the planets are separate dimensions. But please d

**Comment by jeg623** [comment]
Oops not finished lol. But you get my point.

**Comment by DarkGuardsman** [comment]
This is already planned for the medium and large missiles. Which will be added here in a month or two, depending on when the asset developers finish the models.

**Comment by jeg623** [comment]
Asset developers? And I thought it would be difficult to add it in since the planets are considered seperate dimensions.

**Comment by DarkGuardsman** [comment]
Nope, that is very easy to do, the same code to teleport a player is used for all entities. Plus missile already phase out of the world when not in view of a player. This code can also be used to change the missile's dimension location. This way the missile appears in orbit around another planet.

**Comment by jeg623** [comment]
Ah. So what about the cords stuff? For example, cords in the nether not being the same on the overworld. Sort of like that.

**Comment by DarkGuardsman** [comment]
Most likely special systems will be setup for targeting exact locations in each dim. Including entry points and exit points for the missiles.

As for the nether this will be supported separately as it is a magic based dimension. Meaning different ways to fire missiles into these dimensions will be used. For example a cross dim GPS and horizontal launch platform.

**Comment by jeg623** [comment]
I wasn't talking about the nether exactly. I meant the cords difference between the overworld and the nether. Is it the same for planets?

**Comment by jeg623** [comment]
You probably already answered that and I didn't notice lol.

**Comment by DarkGuardsman** [comment]
Not sure it is a problem with planets, but I will not be using the direct coords. Most likely I'll pick an entry point 5K to 20K from the target area. Then spawn or ghost spawn in the missile at this location. Which will then allow the missile to fly towards the target without issues.

**Comment by jeg623** [comment]
Well I hope it goes well. :)

**Comment by jeg623** [comment]
Well I hope it goes well. :) Also, would the missile show up on the screen that lists the planets?

**Comment by DarkGuardsman** [comment]
Not sure I will go as far as editing GC's planet screen. As the code is a bit screwy for GC already enough without me adding ASM. As well missile are not designed to have any early warning systems by default. That will be for radar or deep space radar to detect down the road. Which may have a nice pretty space GUI of it's own.
