### ISSUE TITLE
How to even use normal sized missiles?

### ISSUE THREAD

**Issue by Yanniclord** [BuiltBrokenModding/ICBM#137]
So there are the normal sized missiles in the latest 9th February release of ICBM, but how do i even use them? There is no documentation, and every silo says "Missile will not fit". What to do about this?

**Comment by djoveryde** [comment]
hand held launcher?

**Comment by DarkGuardsman** [comment]
By normal do you mean the standard missiles? If this is the case then you build a missile launcher. To do this place a launcher CPU, then stack 6 launcher frames on top. After which shift-right click the CPU and this will form the launcher. After this you will need to build the missile in the launcher by clicking rods, plates, and parts onto the cpu.

**Comment by DarkGuardsman** [comment]
Here is a video I just created with the setup https://www.youtube.com/watch?v=g9yuNYc5AW0. May still be uploading...
