### ISSUE TITLE
[bug] missile silo dupe

### ISSUE THREAD

**Issue by nugner** [BuiltBrokenModding/ICBM#138]
Breaking a small missile silo will drop 2 items instead of 1.

**Comment by nugner** [comment]
This only occurs if you break the bottom-most block of the silo.  The middle or top ones drop one item like they should.

**Comment by DarkGuardsman** [comment]
Confirmed, I should have it fixed soon.

**Comment by DarkGuardsman** [comment]
Fixed https://github.com/BuiltBrokenModding/ICBM/commit/02b110e126ebc7ab51ffdeb65938c970e1146f91
