### ISSUE TITLE
Lack of Wiki Content

### ISSUE THREAD

**Issue by jeg623** [BuiltBrokenModding/ICBM#142]
I understand that it isn't updated often but the lack of information is extremely surprising. Maybe you could allow the players to write it out? I mean no offense.

**Comment by dmodoomsirius** [comment]
it is on our site atm which is in a different repo. https://github.com/BuiltBrokenModding/site/tree/master/pages/icbm/wiki

**Comment by DarkGuardsman** [comment]
You are more than welcome to contribute to the existing wiki. However, all changes will have to be made through pull requests on the repo dmod linked.
