### ISSUE TITLE
[BUG]  - Function: Standard Launcher Miss Fire - Effect without success 

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/ICBM#145]
This is incredibly difficult to re-produce, it's happened to me twice out of like 200 launches. But sometimes when you click launch, the missiles won't fire. But the fire effects and other things that happen after launch do occur.

It's strange.

**Comment by DarkGuardsman** [comment]
hmm might have collides with the launcher frame or ghost blocks. Is there any indication that the rocket denotated near the silo?

**Comment by GreenCafe** [comment]
No indication whatsoever. The most recent time it happened, was with an ender missile. If that went off, I would've been able to tell.

I should add, the missiles don't go missing. They are still there and are ready to launch again.

**Comment by DarkGuardsman** [comment]
Could be a desync issue if the missile is still in it's tube. I'll check the code in the controller and see if it fires client side by mistake.
