### ISSUE TITLE
Suggestion: ICBM 1.6.4 version port

### ISSUE THREAD

**Issue by jeg623** [BuiltBrokenModding/ICBM#146]
Would it possible to port the 1.6.4 version of ICBM? Just until the 1.7.10 version is released?

**Comment by DarkGuardsman** [comment]
1.7.10 is technically released but there is also a port of the old version in progress. Its called ICBM-Classic but the developers working on it are MIA.

**Comment by jeg623** [comment]
Really? Well if I found some devs for it could be continued to be developed?

**Comment by jeg623** [comment]
BTW I found the latest release on git hub but it's just source code. Do I have to look somewhere else?

**Comment by dmodoomsirius** [comment]
http://builtbroken.net/pages/icbm/1.7/downloads.php

**Comment by DarkGuardsman** [comment]
Right now I rather avoid adding more people to the team. We will get to it down the road, most likely here in a few weeks when college lets out.
