### ISSUE TITLE
Crash on client launch

### ISSUE THREAD

**Issue by IraqiMilitant** [BuiltBrokenModding/ICBM#151]
A NoClassDef error causing crash on client boot.

Crash report here: http://pastebin.com/vqwd4bRX

**Comment by DarkGuardsman** [comment]
The crash is not telling me much, see if you can get me a full log. After you make sure you're using the latest VoltzEngine and ICBM version. As this could be caused by a miss match in versions.

**Comment by IraqiMilitant** [comment]
Full crash log here: http://pastebin.com/t9Z7Rjcm

A bit more in the regular log file: http://pastebin.com/aiNpDbPz

I pulled the most recent version of both (updated 18 or 20 hours ago) only versions available on curseforge.

**Comment by DarkGuardsman** [comment]
I can't seem to replicate the issue with just ICBM and VoltzEngine installed in MultiMC with the same forge version. I do have a few theories to what could cause it.

A) Another mod is using VoltzEngine's API and its outdated. This will require removing mods until it stops crashing

B) Coding Lib is outdated, just delete the file and VoltzEngine will redownload it for you.

**Comment by IraqiMilitant** [comment]
Ok I did some more experimenting and it seems that there is a compat issue between Reika's DragonAPI https://sites.google.com/site/reikasminecraft/dragonapi and ICBM. Once I pull it out then ICBM loads fine.

**Comment by DarkGuardsman** [comment]
I talked to reika it seems he ships the API, easy fix is to open up the DragonAPI and delete com.builtbroken file from it. You can use programs like 7zip to open up the .jar like a .zip file.

 His next few mod version should correct the issue.
