### ISSUE TITLE
Crash after creating the normal missile launcher

### ISSUE THREAD

**Issue by Saleenmaster1** [BuiltBrokenModding/ICBM#156]
Procedure: 
1. Build the launcher (1 computer, 6 frames)
2. Right click the computer with wrench (the thing to create it)
3. Crash with this error message:
A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000228614e7, pid=8612, tid=7756

JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [atio6axx.dll+0xc314e7]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 C:\Users\Leo\AppData\Roaming\.minecraft\hs_err_pid8612.log

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by DarkGuardsman** [comment]
I'll look into it but it might be an issue outside of Minecraft itself. Potentially the game ran out of memory is one of the causes of the error. Check to make sure you are running Minecraft with at least 2GB of ram, if not more. As well if you are using java 7, update to java 8 as it auto increases heap space. Which is used for loading class files and can also cause this error(in theory).

**Comment by DarkGuardsman** [comment]
@Saleenmaster1 Just tested everything in my dev workspace, and live on two PCs. I can not replicate the errors so I will need more information.

1) Repeat building the launcher a few times, including with just the latest version mod installed by itself. As well after you have rebooted your computer and turned off background apps.

2) If the crash still happens I need the C:\Users\Leo\AppData\Roaming.minecraft\hs_err_pid8612.log that the crash noted. I'm unsure what I can do with the log but it might reveal some more detailed information.

3) Try doing anything else and see if the crash still happens. If it does then it may not be the mod itself and could be your install. If this is the case then reinstall MC and forge repeating step 1.

**Comment by Saleenmaster1** [comment]
If i try to do it as a standalone, it works just fine. Using my other mods it results in a crash
heres the crashlog you requested: http://pastebin.com/Rmvw1NfY

**Comment by DarkGuardsman** [comment]
After reviewing the data I can not tell much, from asking in the #minecraftforge channel one of the suggestions was update graphics drivers. Give that a try and see if it changes anything. As well I have to ask why is your java install on your desktop?

**Comment by DarkGuardsman** [comment]
Can you get me a list of mods you have installed. As well add one mod at a time until the crash happens. It looks like it might be an entity that is the source of the crash.

**Comment by Saleenmaster1** [comment]
I dont know why my java is on my desktop, it may be cause im stupid and installed several development kits on my pc. Also netbeans. Ill fetch my modlist asa I get back home

**Comment by DarkGuardsman** [comment]
I would see about re-installing java in programs folder, this might be causing so access issues for java. As the desktop is normally locked per use and can have access issues for software. Still might not be the cause but is worth doing to avoid future issues.

**Comment by Saleenmaster1** [comment]
Okay, updated drivers, wiped java. Everything works again. Thank you for your help :)
