### ISSUE TITLE
ServerSide: Delayed blast code

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM#161]
Could be just my computer, most likely is, but the blast code seems to run very slow. Only seems to happen server side and not client side. Once again could be stress on the computer from running a server and two clients.

**Comment by Andrew2070** [comment]
Not sure if you mean this but missiles come down fairly slowly towards their targets.
The engine exhaust also seems to be pointing downward from the missile as well.
Basically it comes down slow enough that it can easily be avoided by running away at Y:74 (64 sea level)
