### ISSUE TITLE
Silo Controller : Fails to link with Silo Connector

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM#163]
@GreenCafe seems you were right, I confirmed that the controller will not connect with the connector. As well it seems that no interaction is functioning for this block. I honestly think that it is in fact not generating a tile entity but will have to look into this more.

Still the issue does not happen in the dev workspace with forge version 1428. I have yet to update my forge and also think this could be related.

**Comment by GreenCafe** [comment]
See, I'm not entirely insane.

**Comment by DarkGuardsman** [comment]
I didn't think you were, just very odd bug
