### ISSUE TITLE
ReactorCore, ShipCore, etc. shouldn't be considered as ores

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM#192]
My mods adds blocks like ReactorCore, ShipCore, etc.
The ore warhead consider them as ores.

I suggest to blacklist tile entities by default and whitelist GregTech.

**Comment by LemADEC** [comment]
Alternately, we could whitelist on Material.ROCK

**Comment by DarkGuardsman** [comment]
See if the latest version fixed the issue

 I added better checks, a whitelist & blasklist, as well ensured that non-vanilla or ve ores are checked against the furnace recipes.
