### ISSUE TITLE
[BUG] Offset Missile Engine Effect - Missile effect meant for engine msiplaced

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/ICBM#193]
This exists on all missile type. Most predominantly on the standard missile.

On both the small and standard missile, the particles are generated at the tip of the rocket, not where the engine is and where the particles would be assumed to generate from.

On the Standard Missile, the particles generate to the side of the missile, as if there is a second missile right next to it.

I personally can not tell if this was intentional during development, but I don't think it should stay. Even if it was originally intentional.

**Comment by DarkGuardsman** [comment]
Known issue
