### ISSUE TITLE
[Suggestion] Have AMS Turret snap to origin and default position when not locked on

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/ICBM#194]
Currently, after the AMS turret locks and tracks a missile and it disappears without the AMS turret destroying the missile, it will freeze at the position it last saw the missile and won't reset. So it can freeze in weird positions until it sees a new missile or is replaced.

**Comment by DarkGuardsman** [comment]
On the todo list, including random rotation and rotation limiting
