### ISSUE TITLE
[Question] Will Radar Stations be reimplemented?

### ISSUE THREAD

**Issue by Andrew2070** [BuiltBrokenModding/ICBM#196]
Hey,

I re read the information Built Broken Modding Site, and it shows that radar stations were removed as they are not part of the original focus of the mod, i was wondering if they would be re-added because i don't think many people want to rely on an anti aircraft gun to shoot down incoming nukes..

I believe it was mentioned it was going to be re added but i dont remember exactly what was said.
Thus in case if it was mentioned earlier over IRC or here please excuse my stupidity.

(Trying to know when/how to prepare lua code ahead of time)

**Comment by DarkGuardsman** [comment]
I small version will be re-added to ICBM but another mod will add high tier versions.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/issues/184
