### ISSUE TITLE
[BUG] Rocket Effect

### ISSUE THREAD

**Issue by Andrew2070** [BuiltBrokenModding/ICBM#199]
Hey,

The rockets that are fired from the rocket launcher have a slight bug,
the pink light is slower than the missile and follows under the rocket
So when you see the rocket in flight it appears as if the exhaust is coming from underneath.
Plus it continues to exist for a few ticks after the initial explosion/contact by the rocket.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/issues/193
