### ISSUE TITLE
[Question] Flight Times

### ISSUE THREAD

**Issue by Andrew2070** [BuiltBrokenModding/ICBM#200]
Hi Andrew here,
After reading over the flight times of each missile i wanted to ask if they were based on in game time or actual time, i thought it would be in game but was not sure exactly due to the reason for the times.

1 MC HOUR => 50 Seconds
1 MC DAY => 20 Minutes.

The flight time i read was 20 Hours, so would that mean 50x20 = 1000 real seconds = 27.7 real minutes.

Although that seems realistic, is there anyway it could be decreased to 10 minute strike time?
Plus on a side note these missiles are chunk loaders correct? or they'll vanish 10 chunks away.

**Comment by DarkGuardsman** [comment]
Real world time, though this all depends on how fast the server runs. If it runs slower than the missile will fly longer. The idea behind the super long time is the missiles travel with realistic travel speeds. So nuking an area 100Km from your base would take several mins to travel towards. Not fast, but also balanced towards building bases closer to your enemies. As well the times are maximum, most missiles have a much lower lifespan. Plus the system is not fully implemented so times will vary a lot.

Also, there is no chunkloading, the missiles leave the map and use a timer system. This way they can keep flying without chunkloading the map, better for performance.
