### ISSUE TITLE
[bug] crash on missile networks

### ISSUE THREAD

**Issue by nugner** [BuiltBrokenModding/ICBM#206]
Destroying missile silos and then opening the GUI of a launch controller they were previously connected to causes a null pointer exception crash.  

Log here : http://pastebin.com/Bwz4Rb1n

**Comment by dmodoomsirius** [comment]
did you try to reproduce this issue with just VoltzEngine and ICBM?

**Comment by DarkGuardsman** [comment]
Will take me a while to debug but looks like some data was empty when sent to the client. Easy bug to over look but very hard to track down.

**Comment by DarkGuardsman** [comment]
I could not replicate the issue on my machine, something tells me its rather rare setup issue. However, I did patch a section that looked like it could be the cause. Download the latest dev version and see if that fixes the issue.
