### ISSUE TITLE
[Question] Progress.

### ISSUE THREAD

**Issue by Andrew2070** [BuiltBrokenModding/ICBM#209]
Hi

Just wanted to know what the current progress is.
What exactly are you all heading for in the next stable release?

~Thanks

**Comment by Andrew2070** [comment]
I mean, you guys have seen this right?

http://aidancbrady.com/defensetech/

**Comment by dmodoomsirius** [comment]
Yes we are aware of what Aidan is doing

**Comment by DarkGuardsman** [comment]
Ya, aidan has permission to make that version. However, he has already been told to change the models out.

As for an ETA, I have two part time jobs so progress is going to be slower. Though I never really give out ETAs due to the nature of modding. Which prevents releasing versions on time, etc.
