### ISSUE TITLE
Missile items not consumed

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM#211]
When breaking a launcher frame, missile gets dropped as an item.
Said item isn't consumed when loading it into a launcher, hence making a free copy of it...

Reproduced initially in SMP.
Confirmed in SSP with ICBM-1.7.10-2.10.2b214-dev-universal + VoltzEngine-1.7.10-0.15.10b160-dev-universal-3

**Comment by DarkGuardsman** [comment]
Confirmed, will fix soon... the issue is most likely that I neglected to code the machine to consume the missile from the player's inventory. I never really intended for the player to ever get the actual missile item for the standard missile.
