### ISSUE TITLE
Crashes on Server

### ISSUE THREAD

**Issue by jobensingh** [BuiltBrokenModding/ICBM#212]
Im currently running the latest version of the mod for 1.7.10, and whenever I start up the server I get a crash, preventing it from starting. I am playing with many differen't mods, so Its likely a conflicting with one of them. Here is the crash report http://pastebin.com/7nZAJe6R . Also pointing out server works fine without ICBM and the other two mods it requires. The client works fine.

**Comment by dmodoomsirius** [comment]
Does this issue happen with forge? We don't support cauldron.

**Comment by DarkGuardsman** [comment]
yep that is an issue with cauldron, its conflicting with the ASM checks that ensure things are working. I could add a config to disable the check. However, as dmod noted we do not support cauldron due to the difficulty of fixing issues related to it. Plus as far as I understand the system was discontinued a while back.

**Comment by dmodoomsirius** [comment]
There have been many new variations. Kcauldron, thermos are the newest ones I know of.

**Comment by jobensingh** [comment]
It would be nice if you could add that to the configuration, since the mod is for 1.7, and since they decided to discontinue cauldron and work on sponge, which is only available in 1.8. I haven't tried any other variations of cauldron, but I'll be sure to see if they work, if and until the config is added

**Comment by DarkGuardsman** [comment]
Config has been added, however, the next version of Voltz Engine may not be released for a few more weeks. I would also like to point out that if the ASM testing failed then a few of the ASM injections failed as well. Which most likely will cause things like the block update triggers to not function.
