### ISSUE TITLE
Crash after condensing missile cases with ProjectE

### ISSUE THREAD

**Issue by Kaihatsujin** [BuiltBrokenModding/ICBM#226]
I tried to condense small missile casings on my private server and have since crashed every time when I try to join. This is the crash report I got: http://pastebin.com/gKXzQ0cE

**Comment by sinkillerj** [comment]
This is a null NBT issue, ProjectE is creating it without NBT and there is no code in ICBM to handle the NBT being missing at that stage. Try adding it to your PE NBT whitelist.

**Comment by DarkGuardsman** [comment]
Most likely is related to project E, and I will be working on this issue later today. Just need to finish up some freelancing work this morning and download the project E API.
