### ISSUE TITLE
Missile Station Causing Crash

### ISSUE THREAD

**Issue by rpc123** [BuiltBrokenModding/ICBM#237]
@DarkGuardsman 
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 11/26/16 9:54 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: com.builtbroken.mc.prefab.inventory.InventoryUtility.dropItemStack(Lcom/builtbroken/mc/lib/transform/vector/Location;Lnet/minecraft/item/ItemStack;)V
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.ejectCraftingItems(TileSmallMissileWorkstation.java:152)
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.update(TileSmallMissileWorkstation.java:123)
	at com.builtbroken.mc.prefab.tile.Tile.func_145845_h(Tile.java:192)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.ejectCraftingItems(TileSmallMissileWorkstation.java:152)
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.update(TileSmallMissileWorkstation.java:123)
	at com.builtbroken.mc.prefab.tile.Tile.func_145845_h(Tile.java:192)

-- Block entity being ticked --
Details:
	Name: icbm:SmallMissileWorkStation // com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstationClient
	Block type: ID #165 (tile.icbm:missileworkstation // com.builtbroken.mc.prefab.tile.BlockTile)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-38,70,245), Chunk: (at 10,4,5 in -3,15; contains blocks -48,0,240 to -33,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #165 (tile.icbm:missileworkstation // com.builtbroken.mc.prefab.tile.BlockTile)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['clohesy123'/811, l='MpServer', x=-39.51, y=71.62, z=245.02], MCH_ViewEntityDummy['McHeliDummyEntity'/813, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 894, 903
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-44,64,252), Chunk: (at 4,4,12 in -3,15; contains blocks -48,0,240 to -33,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 412 game time, 412 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 116 total; [EntityChicken['Chicken'/653, l='MpServer', x=-104.81, y=68.00, z=196.81], EntityChicken['Chicken'/654, l='MpServer', x=-105.50, y=68.00, z=194.50], EntityChicken['Chicken'/655, l='MpServer', x=-106.50, y=68.00, z=196.50], EntityChicken['Chicken'/656, l='MpServer', x=-105.50, y=68.00, z=195.50], EntityChicken['Chicken'/667, l='MpServer', x=-73.50, y=70.00, z=308.50], EntityChicken['Chicken'/668, l='MpServer', x=-73.53, y=70.00, z=305.34], EntityChicken['Chicken'/669, l='MpServer', x=-74.50, y=70.00, z=304.50], EntityChicken['Chicken'/670, l='MpServer', x=-73.50, y=70.00, z=306.50], EntityChicken['Chicken'/675, l='MpServer', x=-71.50, y=59.00, z=206.50], EntityChicken['Chicken'/676, l='MpServer', x=-68.50, y=64.00, z=209.50], EntityChicken['Chicken'/677, l='MpServer', x=-69.50, y=64.00, z=208.50], EntityChicken['Chicken'/678, l='MpServer', x=-71.50, y=59.00, z=206.50], EntityChicken['Chicken'/679, l='MpServer', x=-65.50, y=71.00, z=251.50], EntityChicken['Chicken'/680, l='MpServer', x=-65.50, y=71.00, z=251.50], EntityChicken['Chicken'/681, l='MpServer', x=-56.53, y=71.00, z=260.47], EntityChicken['Chicken'/682, l='MpServer', x=-64.53, y=70.00, z=245.72], EntityChicken['Chicken'/683, l='MpServer', x=-69.50, y=70.00, z=264.50], EntityChicken['Chicken'/684, l='MpServer', x=-69.50, y=70.00, z=267.50], EntityChicken['Chicken'/685, l='MpServer', x=-61.59, y=71.00, z=260.63], EntityChicken['Chicken'/686, l='MpServer', x=-71.50, y=70.00, z=267.50], EntityChicken['Chicken'/687, l='MpServer', x=-70.50, y=70.00, z=317.50], EntityChicken['Chicken'/688, l='MpServer', x=-68.50, y=71.00, z=317.50], EntityChicken['Chicken'/689, l='MpServer', x=-68.50, y=71.00, z=318.50], EntityChicken['Chicken'/690, l='MpServer', x=-70.50, y=70.00, z=317.50], EntityChicken['Chicken'/695, l='MpServer', x=-49.50, y=64.00, z=199.50], EntityChicken['Chicken'/696, l='MpServer', x=-50.44, y=68.00, z=197.53], EntityChicken['Chicken'/697, l='MpServer', x=-50.59, y=68.00, z=195.19], EntityChicken['Chicken'/698, l='MpServer', x=-52.50, y=68.00, z=197.50], EntityChicken['Chicken'/699, l='MpServer', x=-64.41, y=70.00, z=245.16], EntityChicken['Chicken'/700, l='MpServer', x=-54.47, y=70.00, z=250.34], EntityChicken['Chicken'/701, l='MpServer', x=-49.50, y=70.00, z=241.50], EntityChicken['Chicken'/702, l='MpServer', x=-49.50, y=70.00, z=245.50], EntityChicken['Chicken'/715, l='MpServer', x=-30.50, y=68.00, z=209.50], EntityChicken['Chicken'/716, l='MpServer', x=-29.53, y=68.00, z=201.53], EntityChicken['Chicken'/717, l='MpServer', x=-35.38, y=68.00, z=203.59], EntityChicken['Chicken'/718, l='MpServer', x=-25.50, y=68.00, z=206.50], EntityChicken['Chicken'/723, l='MpServer', x=6.50, y=64.00, z=252.50], EntityChicken['Chicken'/724, l='MpServer', x=5.50, y=64.00, z=250.50], EntityChicken['Chicken'/725, l='MpServer', x=7.50, y=64.00, z=250.50], EntityChicken['Chicken'/726, l='MpServer', x=7.50, y=62.08, z=248.50], EntityHorse['Horse'/759, l='MpServer', x=37.22, y=64.00, z=303.47], EntityHorse['Horse'/761, l='MpServer', x=39.50, y=64.00, z=305.00], EntityClientPlayerMP['clohesy123'/811, l='MpServer', x=-39.51, y=71.62, z=245.02], MCH_ViewEntityDummy['McHeliDummyEntity'/813, l='MpServer', x=0.00, y=-4.00, z=0.00], EntitySkeleton['Skeleton'/998, l='MpServer', x=-95.50, y=34.00, z=279.50], EntitySpider['Spider'/999, l='MpServer', x=-4.94, y=53.62, z=280.38], EntityBat['Bat'/1001, l='MpServer', x=18.66, y=52.00, z=317.66], EntityZombie['Zombie'/1028, l='MpServer', x=-70.41, y=30.00, z=279.97], EntityBat['Bat'/1029, l='MpServer', x=12.63, y=54.00, z=319.00], EntityBat['Bat'/1030, l='MpServer', x=-7.84, y=31.92, z=222.25], EntityBat['Bat'/1031, l='MpServer', x=-9.03, y=32.39, z=225.09], EntityZombie['Zombie'/1043, l='MpServer', x=-8.50, y=53.00, z=297.50], EntitySkeleton['Skeleton'/1044, l='MpServer', x=-14.50, y=41.00, z=251.50], EntityBat['Bat'/1056, l='MpServer', x=-14.06, y=32.45, z=229.42], EntityBat['Bat'/1063, l='MpServer', x=-7.66, y=32.00, z=220.75], EntityBat['Bat'/1064, l='MpServer', x=-8.29, y=31.80, z=223.54], EntityBat['Bat'/1066, l='MpServer', x=16.03, y=16.00, z=270.75], EntityZombie['Zombie'/1076, l='MpServer', x=-98.50, y=17.00, z=281.50], EntitySkeleton['Skeleton'/1077, l='MpServer', x=-42.50, y=21.00, z=298.50], EntityBat['Bat'/1078, l='MpServer', x=-5.52, y=34.38, z=217.96], EntityBat['Bat'/1102, l='MpServer', x=-7.50, y=31.82, z=222.22], EntityCreeper['Creeper'/1122, l='MpServer', x=3.91, y=23.00, z=301.75], EntityZombie['Zombie'/1178, l='MpServer', x=-99.50, y=17.00, z=279.44], EntityZombie['Zombie'/1179, l='MpServer', x=-94.91, y=16.00, z=282.44], EntityZombie['Zombie'/1180, l='MpServer', x=-102.50, y=17.00, z=279.50], EntityZombie['Zombie'/1182, l='MpServer', x=-2.31, y=40.00, z=207.56], EntityZombie['Zombie'/1183, l='MpServer', x=-57.34, y=50.00, z=211.97], EntitySkeleton['Skeleton'/1184, l='MpServer', x=-62.50, y=54.00, z=226.09], EntityCreeper['Creeper'/1185, l='MpServer', x=-4.50, y=53.00, z=278.34], EntityCreeper['Creeper'/1186, l='MpServer', x=-6.50, y=53.00, z=279.50], EntityCreeper['Creeper'/1187, l='MpServer', x=8.50, y=14.00, z=261.50], EntityBat['Bat'/1188, l='MpServer', x=-116.97, y=25.00, z=316.34], EntityZombie['Zombie'/1196, l='MpServer', x=5.50, y=14.00, z=258.50], EntityZombie['Zombie'/1205, l='MpServer', x=4.50, y=14.00, z=259.50], EntityCreeper['Creeper'/1208, l='MpServer', x=7.50, y=14.00, z=260.50], EntityBat['Bat'/1223, l='MpServer', x=-62.28, y=43.10, z=245.31], EntityBat['Bat'/1224, l='MpServer', x=13.66, y=25.00, z=316.59], EntityBat['Bat'/1225, l='MpServer', x=10.25, y=25.00, z=313.34], EntityBat['Bat'/1226, l='MpServer', x=9.53, y=25.00, z=310.47], EntityBat['Bat'/1227, l='MpServer', x=14.72, y=25.00, z=314.84], EntityBat['Bat'/1228, l='MpServer', x=-38.53, y=51.10, z=291.25], EntitySkeleton['Skeleton'/1231, l='MpServer', x=-55.45, y=51.00, z=219.77], EntitySkeleton['Skeleton'/1232, l='MpServer', x=-54.88, y=51.00, z=224.53], EntitySkeleton['Skeleton'/1233, l='MpServer', x=-61.03, y=51.00, z=218.72], EntitySkeleton['Skeleton'/1316, l='MpServer', x=-96.50, y=40.00, z=223.50], EntitySkeleton['Skeleton'/1317, l='MpServer', x=-101.50, y=40.00, z=221.50], EntityCreeper['Creeper'/1333, l='MpServer', x=19.50, y=55.00, z=286.50], EntityZombie['Zombie'/1335, l='MpServer', x=-23.50, y=24.00, z=313.50], EntitySkeleton['Skeleton'/1356, l='MpServer', x=-46.50, y=35.00, z=176.50], EntitySpider['Spider'/1358, l='MpServer', x=-62.72, y=54.00, z=267.53], EntityZombie['Zombie'/1359, l='MpServer', x=6.50, y=55.00, z=318.50], EntityZombie['Zombie'/1360, l='MpServer', x=-50.50, y=35.00, z=167.50], EntitySkeleton['Skeleton'/1367, l='MpServer', x=-3.50, y=55.00, z=311.50], EntityZombie['Zombie'/1368, l='MpServer', x=18.50, y=19.00, z=315.50], EntityCreeper['Creeper'/1377, l='MpServer', x=18.50, y=19.00, z=317.50], EntitySpider['Spider'/1411, l='MpServer', x=7.50, y=34.00, z=306.50], EntityZombie['Zombie'/1413, l='MpServer', x=17.09, y=52.00, z=318.97], EntitySpider['Spider'/1423, l='MpServer', x=9.50, y=40.00, z=280.50], EntitySkeleton['Skeleton'/1424, l='MpServer', x=-117.50, y=25.00, z=321.50], EntityZombie['Zombie'/1509, l='MpServer', x=22.50, y=52.00, z=317.50], EntityZombie['Zombie'/1510, l='MpServer', x=21.50, y=52.00, z=315.50], EntityZombie['Zombie'/1511, l='MpServer', x=25.50, y=52.00, z=316.50], EntityCreeper['Creeper'/1513, l='MpServer', x=-118.50, y=25.00, z=318.59], EntityZombie['Zombie'/1516, l='MpServer', x=-117.50, y=25.00, z=318.50], EntityZombie['Zombie'/1628, l='MpServer', x=-118.50, y=25.00, z=322.50], EntityZombie['Zombie'/1629, l='MpServer', x=-115.31, y=16.00, z=271.97], EntityCreeper['Creeper'/1630, l='MpServer', x=-51.50, y=42.00, z=310.50], EntitySkeleton['Skeleton'/1631, l='MpServer', x=-49.50, y=42.00, z=309.50], EntitySkeleton['Skeleton'/1632, l='MpServer', x=16.50, y=44.00, z=306.50], EntityCreeper['Creeper'/1655, l='MpServer', x=6.50, y=46.00, z=256.50], EntitySkeleton['Skeleton'/1660, l='MpServer', x=3.94, y=33.00, z=240.53], EntityZombie['Zombie'/1672, l='MpServer', x=-92.50, y=44.00, z=294.50], EntityCreeper['Creeper'/1674, l='MpServer', x=8.50, y=51.00, z=287.50], EntityZombie['Zombie'/1765, l='MpServer', x=13.50, y=24.00, z=299.50], EntitySkeleton['Skeleton'/1768, l='MpServer', x=1.50, y=24.00, z=300.50], EntitySkeleton['Skeleton'/1804, l='MpServer', x=3.50, y=24.00, z=300.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 366332032 bytes (349 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_D3 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAAAAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAAAAAAA	BetterFoliage{2.0.14} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.14.jar) 
	UCHIJAAAAAAAAA	VoltzEngine{0.19.21.248} [Voltz Engine] (VoltzEngine-1.7.10-0.19.21b248-dev-universal.jar) 
	UCHIJAAAAAAAAA	icbm{2.10.2.24} [ICBM] (ICBM-1.7.10-2.10.2b24-universal.jar) 
	UCHIJAAAAAAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAAAAAAA	millenaire{6.0.0} [Millénaire] (millenaire-6.0.0.jar) 
	UCHIJAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4364' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 20.19.15.4364, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D3
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.4.0 - Build 20.19.15.4364
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by DarkGuardsman** [comment]
Try updating your Voltz Engine version as it is failing to find the inventory drop method that uses 'Location(world, x, y, z)' instead of 'World, x, y, z' as the old version used

**Comment by rpc123** [comment]
Which version should i use then?

**Comment by dmodoomsirius** [comment]
try https://minecraft.curseforge.com/projects/icbm/files/2344812 and https://minecraft.curseforge.com/projects/voltz-engine/files/2344811 as you are using a old version of icbm.
