### ISSUE TITLE
Ticking Block Entity crash 

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/ICBM#238]
Latest 1.7.10 ICBM version and Forge version.

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 11/28/16 4:54 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: com.builtbroken.mc.prefab.inventory.InventoryUtility.dropItemStack(Lcom/builtbroken/mc/lib/transform/vector/Location;Lnet/minecraft/item/ItemStack;)V
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.ejectCraftingItems(TileSmallMissileWorkstation.java:152)
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.update(TileSmallMissileWorkstation.java:123)
	at com.builtbroken.mc.prefab.tile.Tile.func_145845_h(Tile.java:192)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.ejectCraftingItems(TileSmallMissileWorkstation.java:152)
	at com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstation.update(TileSmallMissileWorkstation.java:123)
	at com.builtbroken.mc.prefab.tile.Tile.func_145845_h(Tile.java:192)

-- Block entity being ticked --
Details:
	Name: icbm:SmallMissileWorkStation // com.builtbroken.icbm.content.crafting.station.small.TileSmallMissileWorkstationClient
	Block type: ID #179 (tile.icbm:missileworkstation // com.builtbroken.mc.prefab.tile.BlockTile)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (104,67,533), Chunk: (at 8,4,5 in 6,33; contains blocks 96,0,528 to 111,255,543), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #179 (tile.icbm:missileworkstation // com.builtbroken.mc.prefab.tile.BlockTile)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Green_Cafe'/218, l='MpServer', x=104.05, y=68.62, z=531.03]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-172,64,256), Chunk: (at 4,4,0 in -11,16; contains blocks -176,0,256 to -161,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 29002 game time, 11022 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 75 total; [EntityItem['item.item.seeds'/52242, l='MpServer', x=93.97, y=66.99, z=525.09], EntityClientPlayerMP['Green_Cafe'/218, l='MpServer', x=104.05, y=68.62, z=531.03], EntitySpider['Spider'/53782, l='MpServer', x=142.19, y=57.00, z=517.72], EntityCreeper['Creeper'/54041, l='MpServer', x=172.50, y=30.00, z=608.50], EntitySkeleton['Skeleton'/52509, l='MpServer', x=118.50, y=22.00, z=556.50], EntityHorse['Horse'/4392, l='MpServer', x=86.03, y=70.00, z=478.81], EntityHorse['Horse'/4393, l='MpServer', x=105.00, y=73.00, z=474.81], EntityHorse['Horse'/4394, l='MpServer', x=102.31, y=69.00, z=499.78], EntitySpider['Spider'/5932, l='MpServer', x=24.74, y=-33.62, z=2.97], EntityHorse['Horse'/4914, l='MpServer', x=161.72, y=71.00, z=463.16], EntityHorse['Horse'/4915, l='MpServer', x=163.13, y=71.00, z=465.34], EntityHorse['Horse'/4916, l='MpServer', x=169.16, y=68.00, z=464.34], EntityHorse['Horse'/4917, l='MpServer', x=163.44, y=69.00, z=461.81], EntityPig['Pig'/5952, l='MpServer', x=110.44, y=67.00, z=607.09], EntityHorse['Horse'/5964, l='MpServer', x=32.56, y=69.00, z=469.13], EntityEnderman['Enderman'/54107, l='MpServer', x=139.50, y=59.00, z=481.50], EntityZombie['Zombie'/54112, l='MpServer', x=159.50, y=48.00, z=565.50], EntityZombie['Zombie'/54113, l='MpServer', x=159.69, y=52.00, z=585.16], EntityBat['Bat'/53102, l='MpServer', x=97.47, y=32.10, z=462.22], EntityBat['Bat'/53103, l='MpServer', x=94.39, y=31.00, z=448.93], EntitySkeleton['Skeleton'/54134, l='MpServer', x=137.56, y=61.00, z=492.06], EntityChicken['Chicken'/5008, l='MpServer', x=60.50, y=74.00, z=550.50], EntityItem['item.item.egg'/53904, l='MpServer', x=57.34, y=72.13, z=547.03], EntityChicken['Chicken'/5009, l='MpServer', x=58.50, y=72.00, z=547.50], EntityItem['item.item.egg'/51601, l='MpServer', x=62.38, y=73.13, z=549.38], EntityChicken['Chicken'/5010, l='MpServer', x=61.53, y=76.00, z=548.31], EntityEnderman['Enderman'/53394, l='MpServer', x=110.78, y=36.00, z=499.69], EntityChicken['Chicken'/5011, l='MpServer', x=60.50, y=70.00, z=540.50], EntityCreeper['Creeper'/53651, l='MpServer', x=126.22, y=22.00, z=598.93], EntitySheep['Sheep'/5012, l='MpServer', x=60.69, y=71.00, z=544.53], EntityCreeper['Creeper'/53652, l='MpServer', x=135.50, y=32.00, z=592.50], EntitySheep['Sheep'/5013, l='MpServer', x=63.50, y=68.00, z=540.50], EntitySheep['Sheep'/5014, l='MpServer', x=63.50, y=71.00, z=543.50], EntitySheep['Sheep'/5015, l='MpServer', x=63.50, y=72.00, z=545.50], EntityHorse['Horse'/6061, l='MpServer', x=35.03, y=69.00, z=465.94], EntityHorse['Horse'/6063, l='MpServer', x=35.75, y=69.00, z=461.38], EntityPig['Pig'/6064, l='MpServer', x=40.84, y=78.00, z=450.47], EntityZombie['Zombie'/5298, l='MpServer', x=-30.06, y=-52.14, z=-24.02], EntitySkeleton['Skeleton'/4276, l='MpServer', x=-47.04, y=-43.48, z=8.23], EntitySkeleton['Skeleton'/52664, l='MpServer', x=109.50, y=53.00, z=590.50], EntitySkeleton['Skeleton'/52666, l='MpServer', x=111.50, y=53.00, z=592.50], EntityItem['item.tile.flower2.tulipOrange'/52163, l='MpServer', x=114.25, y=67.13, z=535.66], EntityItem['item.item.seeds'/52167, l='MpServer', x=110.66, y=67.13, z=539.19], EntityItem['item.tile.flower2.tulipOrange'/52170, l='MpServer', x=116.53, y=67.13, z=533.13], EntityItem['item.tile.flower1.dandelion'/52171, l='MpServer', x=114.19, y=67.13, z=535.31], EntityHorse['Horse'/5838, l='MpServer', x=170.09, y=70.00, z=583.28], EntityHorse['Horse'/5839, l='MpServer', x=170.56, y=71.00, z=585.06], EntityItem['item.tile.flower2.poppy'/52175, l='MpServer', x=114.81, y=67.13, z=527.81], EntityHorse['Horse'/5841, l='MpServer', x=169.84, y=70.00, z=577.84], EntityHorse['Horse'/5842, l='MpServer', x=168.06, y=72.00, z=579.50], EntityItem['item.item.seeds'/52178, l='MpServer', x=107.72, y=67.13, z=526.69], EntityItem['item.tile.flower2.oxeyeDaisy'/52179, l='MpServer', x=116.19, y=67.13, z=529.16], EntityItem['item.tile.flower1.dandelion'/52180, l='MpServer', x=115.69, y=67.13, z=534.75], EntityZombie['Zombie'/53460, l='MpServer', x=115.50, y=39.00, z=494.91], EntityZombie['Zombie'/53461, l='MpServer', x=116.59, y=37.00, z=499.31], EntityItem['item.tile.flower2.poppy'/52184, l='MpServer', x=114.38, y=67.13, z=526.94], EntityCreeper['Creeper'/53464, l='MpServer', x=130.50, y=36.00, z=518.50], EntityItem['item.item.seeds'/52185, l='MpServer', x=115.13, y=67.13, z=535.28], EntityCreeper['Creeper'/53465, l='MpServer', x=130.50, y=36.00, z=520.50], EntitySkeleton['Skeleton'/52445, l='MpServer', x=100.50, y=16.00, z=471.50], EntityZombie['Zombie'/53482, l='MpServer', x=140.50, y=61.00, z=487.03], EntityEnderman['Enderman'/51691, l='MpServer', x=120.50, y=37.00, z=504.50], EntityItem['item.item.egg'/50924, l='MpServer', x=60.53, y=71.13, z=544.13], EntityHorse['Horse'/5870, l='MpServer', x=158.50, y=72.00, z=590.50], EntityHorse['Horse'/5871, l='MpServer', x=162.13, y=72.00, z=589.19], EntityHorse['Horse'/5872, l='MpServer', x=160.44, y=72.00, z=591.41], EntityHorse['Donkey'/54000, l='MpServer', x=114.06, y=66.00, z=611.41], EntityHorse['Horse'/5873, l='MpServer', x=167.28, y=72.00, z=587.06], EntityHorse['Horse'/5874, l='MpServer', x=164.13, y=72.00, z=593.28], EntityPig['Pig'/54003, l='MpServer', x=108.88, y=67.00, z=608.47], EntityPig['Pig'/54005, l='MpServer', x=111.69, y=67.00, z=609.47], EntityHorse['Donkey'/54006, l='MpServer', x=107.56, y=67.00, z=611.88], EntityHorse['Horse'/24823, l='MpServer', x=38.81, y=70.00, z=461.53], EntityEnderman['Enderman'/52730, l='MpServer', x=154.50, y=34.00, z=497.69], EntityZombie['Zombie'/53498, l='MpServer', x=143.44, y=22.00, z=468.06]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 93485752 bytes (89 MB) / 493465600 bytes (470 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	VoltzEngine{0.19.21.248} [Voltz Engine] (VoltzEngine-1.7.10-0.19.21b248-dev-universal.jar) 
	UCHIJAAAA	addictedtored{0.4.0.15} [Addicted To Red] (AddictedToRed-1.7.10-0.4.0b15-universal.jar) 
	UCHIJAAAA	bbm_announcements{0.0.1.3} [Announcements] (Announcement-Mod-1.7.10-0.0.1b3-universal.jar) 
	UCHIJAAAA	assemblyline{0.5.3.12} [Assembly Line] (Assembly-Line-1.7.10-0.5.3b12-dev-universal.jar) 
	UCHIJAAAA	coloredchests{0.0.1.20151209060506} [Colored Chests] (ColoredChests-1.7.10-0.0.1b2.jar) 
	UCHIJAAAA	icbm{2.10.2.24} [ICBM] (ICBM-1.7.10-2.10.2b24-universal.jar) 
	UCHIJAAAA	progressiveworldcleanup{0.15.10.20160616190232} [Progressive World Cleanup] (ProgressiveWorldCleanup-1.7.10-0.15.10b2-dev-universal.jar) 
	UCHIJAAAA	ResonantEngine{3.0.0} [Resonant Engine] (resonant-engine-3.0.0.255-core.jar) 
	UCHIJAAAA	cardboardboxes{0.0.1.5} [Cardboard Boxes] (SBM-CardboardBoxes-1.7.10-0.0.1b5-universal.jar) 
	UCHIJAAAA	smbmagicmirror{0.0.1.13} [SMB Magic Mirror] (SBM-Magic-Mirror-1.7.10-0.0.1b13-universal.jar) 
	UCHIJAAAA	woodenbucket{0.0.3.9} [Wooden Bucket] (WoodenBucket-1.7.10-0.0.3b9-universal.jar) 
	UCHIJAAAA	woodenrails{0.0.1.20150806142027} [Wooden Rails] (WoodenRails-1.7.10-0.0.1b1.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.95' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 375.95, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by DarkGuardsman** [comment]
Update your VE version
