### ISSUE TITLE
Gravity Affect

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/ICBM#244]
In some cases, I am able to trick the game into letting me shoot a missile in the same spot that a gravity missile should be reversing.

It requires a little finessing to make it happen and that's why I marked it as low priority. It is difficult to replicate.

Video of me messing with gravity rockets, go to 3:05 to see the issue happen:
https://youtu.be/QEVwTjH4Zd8?t=185

**Comment by DarkGuardsman** [comment]
Looks find to me
