### ISSUE TITLE
Firing Rocket at players kicks both players from server

### ISSUE THREAD

**Issue by Time6628** [BuiltBrokenModding/ICBM#249]
```
[20:57:24] [Server thread/INFO]: Missile created and fired -> Missile[ 0@dim -227.53x 41.52y -484.13z ]@14841
[20:57:24] [Server thread/INFO]: Missile[ 0@dim -228.70x 40.72y -483.90z ]@14841 impact -230.00x -230.00y -230.00z
```
That is the error. The rocket breaks and the player who you shot at and yourself get kicked from the server.

**Comment by dmodoomsirius** [comment]
does it crash the server? or does it just kick you? is there any more to the log before and after that? if you can https://gist.github.com/ or http://pastebin.com the log for the server that would help me debug it more? what modpack is this?

**Comment by DarkGuardsman** [comment]
See if you can get a client log as well as it is most likely a client net
error

**Comment by DarkGuardsman** [comment]
Replicated the issue with an Anti-matter small missile being shot at a player. Will test the other explosives but it's just a client side piece of code being server side.

**Comment by DarkGuardsman** [comment]
Fixed https://github.com/BuiltBrokenModding/VoltzEngine/commit/12c4b09a75faaff00d8a94c8b37786a216ce9b98
