### ISSUE TITLE
Standing on a rocket right after it hits the ground

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/ICBM#253]
If you shoot straight down at your feet when you're on the ground and jump right when you land on the shell of the missile that just appeared the explosion sound and particle go off multiple times. Plus the missiles are just a bit finicky.

url : https://youtu.be/ahhZU5MFvNU

**Comment by DarkGuardsman** [comment]
That should have been fixed already, are you using the latest build?
