### ISSUE TITLE
Standard missile explodes immediately on silo fire

### ISSUE THREAD

**Issue by JuhaJGamer** [BuiltBrokenModding/ICBM#263]
I press fire from launch Controller or use redstone, either way it explodes immediately destroying the silo and then leaves some particles

**Comment by DarkGuardsman** [comment]
The standard silo is not implemented, hence the WIP on the item tooltip. If you want to fire the missile you need to use the standard launcher frame setup.

https://www.youtube.com/watch?v=MdrxdKoucGo
