### ISSUE TITLE
Offering Help.

### ISSUE THREAD

**Issue by Paralaxus** [BuiltBrokenModding/ICBM#271]
Hello.

I am a fairly popular ModPack Owner (Post Blast), a resigned Moderator for a M.C Community and former Tekkit/FTB administrator for the respective servers of that community (Crafter's Land).

I am offering to help in these areas for the I.C.B.M Development:

1.  Wiki
2. New Ideas
3. Bug Tracking
4. Graphic Design
5. Maybe Models (still learning Blender).
6. GitHub Issue Responses.

I have fairly excellent English, powerful imagination and strong desire for success.
I also have 12-13 days off from 12th Grade, so I think i can be useful for you guys.

I was hoping that if you allow me to join your design/info part of the team I can help speed things up.

Also, I have a couple of ideas for you all:
A) New items for the crafting recipes (Ie. chipsets, guidance systems, wiring etc) [T = Tier]
   - T1/T2/T3 processors, T1/T2/T3 casing, T1/T2/T3 wiring, Inertial Guidance/GPS/GLONASS
   - Processors affect missile range, casing affects dud probability, Guidance = missile range/extra

B) New Model designs for Missiles:
  - I think that your current model for an I.C.B.M is too small. It should look longer and fatter.
  - Or, the missile should look like it is two stages. like this:

              ^^
             ^^^^
             |  |
             |  |
             |  |
             |  |
            /    \ 
            |     |
            |     |
            |     |
            |     |
            |     |
            |     |
            -----

~Best wishes, Andrew.

**Comment by Paralaxus** [comment]
Just google a minuteman III Missile or a Thor Missile.
Kinda what I was hoping for.

**Comment by DarkGuardsman** [comment]
Your welcome to help,  these are community developed projects that anyone can contribute towards. However, let's start with wiki help first and then we can talk about new ideas later. Right now we want to polish and stabilize before we move on to new versions of Minecraft. 

The wiki for ICBM is here https://github.com/BuiltBrokenModding/ICBM-Wiki
Its using a custom json driven system that will be used for both the site and in game handbooks. It's rather easy to edit, with pages using a similar format to HTML, see existing pages as examples.

Additional I have been avoiding tech progress through tiers in ICBM. As I feel this hindered gameplay in ICBM-Classic and in older ICBM versions. The new version is focused on mirroring real world building processes and logic. So a micro missile is not a tier 0 but rather just a small missile designed for RPGs & turrets.

If you want to talk more we have a discord https://discord.gg/MDQ9DrN and teamspeak at buildbroken.com
