### ISSUE TITLE
[Bug] T2 Silo (the red one that says WIP)

### ISSUE THREAD

**Issue by Paralaxus** [BuiltBrokenModding/ICBM#272]
MC Version: 1.7.10
ICBM Version: Latest Alpha Release.
Voltz Version: Latest Alpha Release.

Bug:
Using the T2 Silo (the red WIP one) to launch standard missiles yields unexpected results.

Result:
Missiles do not leave the silo and strike anything, rather they vanish for a split second and re-appear on top of their respective silos but slanted at 20 degree angles.

Screenshots:
[img]http://i.imgur.com/vY43F0j.png[/img]
http://imgur.com/wJcf8Cy

**Comment by DarkGuardsman** [comment]
it says WIP
