### ISSUE TITLE
Failed to load a json file from ICBM 

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/ICBM#289]
https://gist.github.com/dmodoomsirius/9963d8a0aecd19c8db09005fc023eb1a

Might be because i have a space in the name of the path.

**Comment by DarkGuardsman** [comment]
https://github.com/VoltzEngine-Project/Engine/commit/c1acabd2b507910240912c2c4aa9db926d51b7cc

**Comment by DarkGuardsman** [comment]
Fixed https://github.com/VoltzEngine-Project/Engine/commit/46a872d5b31462fbd0133b5023e45b9e6359d42e
