### ISSUE TITLE
ICBM Radar

### ISSUE THREAD

**Issue by mesl** [BuiltBrokenModding/ICBM#291]
Hi,

I installed all the mods you need to have to use icbm classic but it seems like the radar doesn't work,
When i send a missile it won't show up

Kind regards Merlyn

**Comment by dmodoomsirius** [comment]
You posted on the ICBM repo not the [ICBM-Classic](https://github.com/BuiltBrokenModding/ICBM-Classic) repo. I will how ever pass this to @DarkGuardsman and he might have some insight.

**Comment by mesl** [comment]
Alright but thx anyway
