### ISSUE TITLE
Crash on start with inventory gui issues in Idea Dev Environment

### ISSUE THREAD

**Issue by notoriousgtw** [BuiltBrokenModding/ICBM#295]
Log:
[https://pastebin.com/8qQ2cV54](https://pastebin.com/8qQ2cV54)

**Comment by DarkGuardsman** [comment]
Crash looks to be related to NEI failing to ASM the game.

**Comment by notoriousgtw** [comment]
@DarkGuardsman
is nei a requirement for ICBM?
bc i dont have it installed

**Comment by DarkGuardsman** [comment]
It doesn't require NEI, but I might be wrong. It could be one of the dependencies of NEI like code chicken core.
