### ISSUE TITLE
Crash on load due to TileFoFClient error.

### ISSUE THREAD

**Issue by DexLuther** [BuiltBrokenModding/ICBM#297]
Minecraft 1.7.10
Forge 10.13.4.1614
VoltzEngine-1.7.10-1.4.0b96.jar
ICBM-1.7.10-2.15.1b394.jar

**Steps to reproduce:**
1. Drop VoltzEngine into mods folder.
2. Start the Minecraft.
3. Answer Yes to Prompt to Download file.
4. Wait for Minecraft to load to Title Screen.
5. Quit Minecraft.
6. Drop ICBM-1.7.10-2.15.1b394.jar into mods folder.
7. Start Minecraft.

**Actual Result:**
The game loads and then crashes returning the following error:
```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/builtbroken/icbm/content/fof/TileFoFClient
```

**Expected Result:**
The game loads properly

**Notes:**
- Please See attached crash report.
- I'm unsure if the file in step 3 actually downloaded properly. I don't remember the name of the file. It never asked to download it again, so I assume it's because the file is present.
- I attempted to run the game with '-DenableAsmTemplates=false' (without the quotes) to bypass the crash as indicated [here](https://minecraft.curseforge.com/projects/voltz-engine), but the game crashed anyways.

**Crash Report:**
https://pastebin.com/7a4a2pJU

**Comment by DarkGuardsman** [comment]
This may be the best-formatted crash report I have every received.

Anyways try the latest alpha of both VE and ICBM. As the most likely issue is a mismatch between versions.
https://minecraft.curseforge.com/projects/icbm/files/2426466
https://minecraft.curseforge.com/projects/voltz-engine/files/2426939

**Comment by DexLuther** [comment]
> This may be the best-formatted crash report I have every received.

Thanks! I work as a game tester, so it's kinda hard to "turn off" that part of the brain. Especially when reporting issues. lol

Sorry for the late reply, but I used the files you linked and successfully was able to load into my world.

**Side note:**
The link to Voltz Engine found [here](https://minecraft.curseforge.com/projects/icbm) in the description seems to be dead. Something probably changed on Curse's side that changes how links work.

**Comment by dmodoomsirius** [comment]
Thank you for the report on the curse link. I will get to it asap.
