### ISSUE TITLE
Complete Lack of Documentation

### ISSUE THREAD

**Issue by Alex33212** [BuiltBrokenModding/ICBM#298]
There appears to be a total lack of documentation on this mod. The Github wiki is empty and the builtbroken.com wiki page returns a 404 error. Where is the information for how to use this mod?

**Comment by dmodoomsirius** [comment]
It is being worked on. The wiki is barely finished and we do not use the github wiki. I will be disabling that asap.

**Comment by DarkGuardsman** [comment]
Ya its a big issues we have been trying to solve for a while. We are running into a few problems right now. 

A) I have no time to work on the wiki myself
B) No one wants to work on the wiki
C) No one but me knows how to use the mods according to those that have tried to work on the wiki
D) Wiki software is not finished yet, hence the 404

that being said I do have a few tutorial videos on my youtube https://www.youtube.com/user/WNxDarkGuardsman these will be included on the wiki once finished. As well I'm training someone to work on the wiki right now. So it might be a few more weeks and it will be completed.

@dmodoomsirius can you edit the site and add a landing page for those 404 links.

**Comment by Alex33212** [comment]
Thanks for the clarification & tutorial videos. Much appreciated!

**Comment by DarkGuardsman** [comment]
No problem, we also have a discord server if you want to join https://discord.gg/MDQ9DrN. With luck, someone will be on that can answer questions about the mod.

**Comment by dmodoomsirius** [comment]
http://builtbroken.com/pages/icbm/wiki/ is a old wiki but it will help for now.

**Comment by Alex33212** [comment]
Thanks!

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/issues/120
