### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by kavala355** [BuiltBrokenModding/ICBM#309]
Failed to process entry from file /content/icbm/deco/missile.small.json. Make corrections to the file or contact the file's creator for the issue to be fixed.
  Entry = block[{"name":"TileMissile","id":"TileMissile","mod":"icbm","isOpaque":false,"tileEntity":{"id":"TileMissile","class":"com.builtbroken.icbm.content.display.TileEntityWrapperMissile"},"listeners":[{"id":"multiblock","layoutKey":"icbm:TileMissile"}],"subtypes":[{"meta":0},{"meta":1},{"meta":2}]}]

**Comment by DarkGuardsman** [comment]
Your version is outdated for the version of VoltzEngine you are using. As the new volt engine changed JSON loading for metadata blocks to enforce naming each subtype. If you have the latest beta for ICBM use the alpha and I will mark new builds as beta later today.
