### ISSUE TITLE
Radar Gun with Launcher Part Crash

### ISSUE THREAD

**Issue by voidswrath** [BuiltBrokenModding/ICBM#310]
As title says and versions are in crash report. 

Using thermos 1558 server. 

https://pastebin.com/W74VFDc6

**Comment by DarkGuardsman** [comment]
Seems to be failing to locate a method while trying to fire a packet to the server. I want to say your versions are outdated but they're not. So either its an issue with Thermos (which is outdated 1614 is latest) or the versions of ICBM & VE on curse do not use the latest code. I'll check the builds here in a second and test to see if I can replicate. If you can try to update your thermos just to rule out the possibility.

**Notes (Ignore)**
**VE:** 1.9.16.331 
**ICBM:** 2.15.4.499
**Crash Main Section:**
``` 
java.lang.NoSuchMethodError: com.builtbroken.mc.core.network.netty.PacketManager.sendToServer(Lcom/builtbroken/mc/api/data/IPacket;)V
    at com.builtbroken.mc.seven.framework.logic.TileEntityWrapper.sendPacketToServer(TileEntityWrapper.java:241)
    at com.builtbroken.mc.api.tile.node.ITileNode.sendPacketToServer(ITileNode.java:109)
    at com.builtbroken.icbm.content.launcher.TileAbstractLauncher.setTarget(TileAbstractLauncher.java:77)
    at com.builtbroken.icbm.content.items.ItemRadarGun.onItemUse(ItemRadarGun.java:89)
```
**Action:** Right click with radargun on launcher
**Source:** Launcher (client -> server) target sync packet

**Comment by DarkGuardsman** [comment]
Found the issue, something is sending a client only packet to the server.... while on the server already. Editing the code to allow the call to happen without crashing in VoltzEngine but still need to fix the issue in ICBM as well.

**Comment by voidswrath** [comment]
Okay great...I got away with it by manually inputing the cords. This one I was spam placing the launch frames...not sure if its related. Sorry for the bug report spam just been playing around with it https://pastebin.com/VcYq4cZV

**Comment by DarkGuardsman** [comment]
Na, no need to be sorry bug reports are gold. Without people testing randomly I miss the odd bugs like the one you just found. 

Edit: that bug should be fixed in the next version. As well try to make a new ticket per bug. It makes it easier to track what is being fixed :)
