### ISSUE TITLE
Would you guys make a version for MC 1.7.2?

### ISSUE THREAD

**Issue by Frankjyn** [BuiltBrokenModding/ICBM#318]
It is kind of unrealistic to say, but that is the thing I really need. 

I am making a mod pack which have been combined with Archimedes's Ship and Flan's mod. To enlarge the scale of wars, I do need ICBM mod. But I just could not find a site to download, not even Calclavia's. 

Why must MC 1.7.2? Well, I am from China, and since Netease took control of Minecraft China Edition from stupid Mojang AB, it banned almost all mods for MC online and offlines, and players could only purchase monthly to access at most 5 mods, like MouseTweaks, which are also pirated from CurseForge. And here is the thing: if I want to play the REAL Minecraft, I will have to pirate it. And if I pirate, the best version for mutiplayer mode is 1.7.2, which Flan's mod pack is the fullest and Archimedes's Ship runs well. 

I am really hesitate to ask for this from you. And I would like to donate if needed. Feel free to ask for any information.

**Comment by DarkGuardsman** [comment]
I was going to say that I don't have time and that you could try to find someone willing to backport the version. As I'm fully ok with individuals making versions of the mod for versions I do not support... But, you just told me you are pirating the game. I can't help you at all in this case as its a violation of the TOS and EULA of several services. It unfortunate to hear you're in a situation that you can't get a legit copy or use modern mods. However, I can't do anything as I could be removed from GitHub and other sites for assisting in violating copyright.

**Comment by KitsuneAlex** [comment]
> It is kind of unrealistic to say, but that is the thing I really need.
> 
> I am making a mod pack which have been combined with Archimedes's Ship and Flan's mod. To enlarge the scale of wars, I do need ICBM mod. But I just could not find a site to download, not even Calclavia's.
> 
> Why must MC 1.7.2? Well, I am from China, and since Netease took control of Minecraft China Edition from stupid Mojang AB, it banned almost all mods for MC online and offlines, and players could only purchase monthly to access at most 5 mods, like MouseTweaks, which are also pirated from CurseForge. And here is the thing: if I want to play the REAL Minecraft, I will have to pirate it. And if I pirate, the best version for mutiplayer mode is 1.7.2, which Flan's mod pack is the fullest and Archimedes's Ship runs well.
> 
> I am really hesitate to ask for this from you. And I would like to donate if needed. Feel free to ask for any information.

http://howoldisminecraft1710.today/

**Comment by KitsuneAlex** [comment]
But srsly, that is unfortunate but our hands are tied in this situation, sorry :/
