### ISSUE TITLE
Change recipes

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM#38]
Current recipes are either to expensive for minor explosives or two vanilla for high tier explosives. It also make very little since that low tier explosives be used to make high tier ones. We should change the explosives to be crafted using bomb parts. As well be crafted from scratch without using parts from other crafted explosives.

TODO
1) Add bomb casing( tier 1, 2, 3)
2) Add bomb trigger
3) Add explosive charge
4) Add timer circuit
5) Add proximity circuit
6) Add GPS circuit(for high tier guide explosives)
7) Add fluid canister(for fire explosives)
8) Teleportation Core(ender explosive)
9) Shrapnel(for fragment explosive)

**Comment by louisw22** [comment]
please make this high priority, it will make the mod useable

**Comment by DarkGuardsman** [comment]
Ya this is high up the priority list but still bellow some of the main features. Like the missile and warhead work tables.

**Comment by louisw22** [comment]
fair enough
