### ISSUE TITLE
OpenComputers support | enhancement

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM#46]
Opencomputers support would be nice for checking wether a launchpad is empty or not, setting coördinates, getting current status (ready to launch/not enough energy) and of course launching missiles. It would also be nice for radar stations, not sure if these were going to be implemented in ICBM though.

**Comment by DarkGuardsman** [comment]
It has been done

**Comment by dmodoomsirius** [comment]
\o/
