### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by MKVollmer25** [BuiltBrokenModding/ICBM#51]
I was playing ICBM beta 37, and I got this crash:

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 12/27/14 10:24 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.builtbroken.icbm.ICBM
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:502)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.builtbroken.icbm.ICBM
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    ... 10 more
Caused by: java.lang.NoClassDefFoundError: resonant/lib/mod/AbstractMod
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 37 more
Caused by: java.lang.ClassNotFoundException: resonant.lib.mod.AbstractMod
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 41 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 170184760 bytes (162 MB) / 505413632 bytes (482 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1231 Minecraft Forge 10.13.2.1231 Optifine OptiFine_1.7.10_HD_U_B1 88 mods loaded, 88 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.85.1231} [Forge Mod Loader](modpack.jar) Unloaded->Constructed
    Forge{10.13.2.1231} [Minecraft Forge](modpack.jar) Unloaded->Constructed
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.3.73} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.73-universal.jar) Unloaded->Constructed
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed
    BuildCraft|Core{6.2.2} [BuildCraft](buildcraft-6.2.2.jar) Unloaded->Constructed
    BuildCraft|Transport{6.2.2} [BC Transport](buildcraft-6.2.2.jar) Unloaded->Constructed
    BuildCraft|Silicon{6.2.2} [BC Silicon](buildcraft-6.2.2.jar) Unloaded->Constructed
    BuildCraft|Builders{6.2.2} [BC Builders](buildcraft-6.2.2.jar) Unloaded->Constructed
    BuildCraft|Energy{6.2.2} [BC Energy](buildcraft-6.2.2.jar) Unloaded->Constructed
    BuildCraft|Factory{6.2.2} [BC Factory](buildcraft-6.2.2.jar) Unloaded->Constructed
    IC2{2.2.646-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.646-experimental.jar) Unloaded->Constructed
    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed
    SlimevoidLib{2.0.4.6} [Slimevoid Library](SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed
    DynamicTransport{0.1.2.0} [Dynamic Transport](DynamicTransport-0.1.2.0.jar) Unloaded->Constructed
    flansmod{4.7.0} [Flan's Mod](Flans Mod-1.7.10-4.7.0.jar) Unloaded->Constructed
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed
    GalacticraftCore{3.0.5} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.5.219.jar) Unloaded->Constructed
    GalacticraftMars{3.0.5} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.5.219.jar) Unloaded->Constructed
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed
    IC2NuclearControl{2.0.8c} [Nuclear Control 2](IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed
    ResonantEngine{3.0.0} [Resonant Engine](resonant-engine-3.0.0.255-core.jar) Unloaded->Constructed
    icbm{2.2.0.1} [ICBM](ICBM-1.7.10-2.2.0b37.jar) Unloaded->Errored
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed
    Railcraft{9.3.1.0} [Railcraft](Railcraft_1.7.10-9.3.1.0.jar) Unloaded->Constructed
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
    Mekanism{7.1.1} [Mekanism](Mekanism-1.7.10-7.1.1.136.jar) Unloaded->Constructed
    MekanismGenerators{7.1.1} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.1.136.jar) Unloaded->Constructed
    MekanismTools{7.1.1} [MekanismTools](MekanismTools-1.7.10-7.1.1.136.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed
    numina{0.4.0.99} [Numina](Numina-0.4.0.99.jar) Unloaded->Constructed
    powersuits{0.11.0.175} [MachineMuse's Modular Powersuits](ModularPowersuits-0.11.0.175.jar) Unloaded->Constructed
    cfm{3.3.6} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.6%281.7.10%29.jar) Unloaded->Constructed
    NBTEdit{1.7.2.2} [In-game NBTEdit](NBTEdit_1.7.10.jar) Unloaded->Constructed
    powersuitaddons{@VERSION@} [Modular Powersuits Addon](powersuitaddons-1.7.10-900.jar) Unloaded->Constructed
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    rivalrebels{1.7.10A} [Rival Rebels](rivalrebels-1.7.10A.jar) Unloaded->Constructed
    secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.376.jar) Unloaded->Constructed
    Sync{4.0.0} [Sync](Sync-4.0.0.jar) Unloaded->Constructed
    TF2Dispenser{1.7.10} [TF2 Dispenser](TF2Dispenser-1.7.10.jar) Unloaded->Constructed
    TF2Sentry{1.7.10} [TF2 Sentry](TF2Sentry-1.7.10.jar) Unloaded->Constructed
    TF2TeamAddon{1.7.10} [TF2 TeamAddon](TF2TeamAddon-1.7.10.jar) Unloaded->Constructed
    TF2Teleporter{1.7.10} [TF2 Teleporter](TF2Teleporter-1.7.10.jar) Unloaded->Constructed
    TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded->Constructed
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed
    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed

**Comment by Chootch7097** [comment]
i've been having the same problem. It has something to do with buildcraft

**Comment by DarkGuardsman** [comment]
Most likely it's not the same crash unless you are using a version that is over 2 years old. 

If you are using the latest version, open a new issue  with your crash report posted from http://pastebin.com/ or a site similar. That way I can see what the problem is and hopefully solve it sometime this week.

**Comment by Chootch7097** [comment]
I was able to fix it but thank you.

**Comment by Chootch7097** [comment]
I did need Resonant Engine to make it work

**Comment by DarkGuardsman** [comment]
ah cool, as a side note due to how old that version is I wouldn't have been able to help you much anyways. Especially since Resonant Engine is no longer a supported project and ICBM's code base is almost 100% different now.
