### ISSUE TITLE
Error with download links

### ISSUE THREAD

**Issue by djoveryde** [BuiltBrokenModding/ICBM#56]
Unable to download any of the new icbm updates, just get 404 error

**Comment by DarkGuardsman** [comment]
I see what happened, just remove the the last bit and it should simi work. I'll fix it as soon as i can but i may need to wait on @dmodoomsirius to change the build server.

**Comment by Timorr** [comment]
What do you mean by "just remove the last bit"?

**Comment by djoveryde** [comment]
When you click the download link you get for example:

http://ci.builtbroken.com/maven/icbm/ICBM/http:/adf.ly/2380428/

Just remove the http:/adf.ly/2380428/

So it then becomes:

http://ci.builtbroken.com/maven/icbm/ICBM/

**Comment by DarkGuardsman** [comment]
ya what @djoveryde suggested will work.

 Also i have fixed the download page plugin, but a new build will not be out for a day or so. Which means that the page on the site will not update either. As the build server needs to run in order to trigger the creation of a new page.

**Comment by mailmindlin** [comment]
It appears that the location [[http://ci.builtbroken.com/maven/icbm/ICBM]] doesn't exist. the furthest that I could go down the directory tree was [[https://ci.builtbroken.com/maven/]].

**Comment by DarkGuardsman** [comment]
looks like the server went off line thats why you can't reach the maven folder

**Comment by mailmindlin** [comment]
No, I got a 404, which means that the server is online, I was able to connect to it, but the location /maven/icbm/ICBM did not exist.

**Comment by dmodoomsirius** [comment]
I am reworking the scripts and the maven so it will be down for now.

**Comment by mailmindlin** [comment]
Can you also just put the compiled JARs with the releases on github? It would be a lot easier.

**Comment by dmodoomsirius** [comment]
not with the current script setup. i will try but no promises

**Comment by DarkGuardsman** [comment]
All builds are alpha builds so i rather not clutter up github with them. As well i do not want to have downloads hosted on github. That is what the maven is for and once it is fully setup there will not be 404 issues. 

Also the server was offline shortly as i was getting no response and the main page was gone when i did. Either way it doesn't matter as there are no downloads in the maven currently.

**Comment by dmodoomsirius** [comment]
The maven is now up and running so are downloads.
