### ISSUE TITLE
Why do you remove Defensive Stuff?

### ISSUE THREAD

**Issue by Timorr** [BuiltBrokenModding/ICBM#58]

**Comment by dmodoomsirius** [comment]
Rewrite it may be added back or it may be added into a new mod

**Comment by Timorr** [comment]
Closed in a second... wow

**Comment by Timorr** [comment]
You are fast

**Comment by DarkGuardsman** [comment]
Yes, anything that is not a missile will be placed into another mod. The reason behind this is to make it very easy to update and continue development for ICBM. Cluttering it up with a lot of content, even though related, make it a pain to work on. It also makes it hard to create new content as the theme become way to broad.
