### ISSUE TITLE
How do I put this mod on my minecraft 1.7.10?

### ISSUE THREAD

**Issue by Atum262** [BuiltBrokenModding/ICBM#60]
Hey guys, I would like to put the mod ICBM 2.3.0 on my minecraft 1.7.10, but I have no idea how to do this, since I already have the forge, and when I download the mod in this site: https://github.com/BuiltBrokenModding/ICBM/tree/2.3.0, I download a .zip file with the ICBM 2.3.0 folder within it, what do I do to put this mod to work on my minecraft?

I wouldn't have to have the mod .jar file to put into the mod folder in the .minecraft folder? That is, the core of the mod? This site provides a mod or only the code of it? Please anyone help me.

**Comment by Parker8283** [comment]
Read the Readme. You are downloading the source code, not the mod. Download the mod here: http://builtbroken.com/icbm-downloads/

**Comment by Parker8283** [comment]
nevermind seems to be down. Anways, you are downloading the source code, not the mod.

**Comment by Atum262** [comment]
oks, thank you

**Comment by dmodoomsirius** [comment]
We are changing engines so we wiped all the old builds once we make sure its working we will have downloads on that page.

**Comment by minwoo5201** [comment]
does latest version fully work? Recent versions I checked were all incomplete dev version though...

**Comment by dmodoomsirius** [comment]
right now we nuked the maven since we are changing engines. the downloads page will be updated once we get everything ready.

**Comment by Atum262** [comment]
ok
