### ISSUE TITLE
modflag option working?

### ISSUE THREAD

**Issue by djoveryde** [BuiltBrokenModding/ICBM#63]
Just checking the modflag command is installed and working correctly as previous 1.6.4 would loose its modflag ban_icbm setting after server restart making any protected zones open to attack.

**Comment by DarkGuardsman** [comment]
1.7.10 we do not currently have modflags as of yet. @dmodoomsirius was working on the new system but its not high priority. Especially since ICBM still has a lot of content that needs to be brought back up.
