### ISSUE TITLE
Infinite Loop Cuboid Subtract

### ISSUE THREAD

**Issue by MrBretze** [BuiltBrokenModding/ICBM#65]
In dont :/ http://paste.ee/p/tMfMt i juste pose 1 loaded warded :/

**Comment by DarkGuardsman** [comment]
Just fixed that issue actual a few mins ago in Voltz Engine. I'll have a new build out soon with the patch.

**Comment by DarkGuardsman** [comment]
Also i noticed another issue in the craft you sent me and made a report for Calclavia. http://tracker.calclavia.com/issue/RE-52 looks like his reflection for the potion array is  no longer functioning.

**Comment by DarkGuardsman** [comment]
ci.builtbroken.com/maven/dev/builtbroken/voltzengine/VoltzEngine/1.7.10-0.0.0b51/VoltzEngine-1.7.10-0.0.0b51-dev.jar

**Comment by MrBretze** [comment]
Thanks
