### ISSUE TITLE
Missing Sound files

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM#67]
ICBM is trying to play a few sound files but as normal is failing to do so. This may be due to the sounds.json not being setup yet.

**Comment by louisw22** [comment]
@DarkGuardsman Please make this a priority, fixing the current mod should be more important than adding new features ot it

**Comment by louisw22** [comment]
http://starlogs.net/#BuiltBrokenModding/ICBM

**Comment by dmodoomsirius** [comment]
@louisw22 its being rewritten. So new content is being added because of that.

**Comment by DarkGuardsman** [comment]
Right now we have zero sound files to use. This is why this has not been fixed as i don't want to recycle the old sound files. Most of them did not fit the objects well.

**Comment by Hennamann** [comment]
Some progress has been made, a sounds.json files was added recently to prepare for sounds.

**Comment by louisw22** [comment]
Thanks

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/commit/139420e61921909c784868ca026a24b1fe4e4e4c
