### ISSUE TITLE
How do I install the ICBM mod in my minecraft 1.7.10?

### ISSUE THREAD

**Issue by Atum262** [BuiltBrokenModding/ICBM#71]
Guys, I'm doing something wrong time to put the mod.
I put the ICBM and the Voltz engine in my mod folder ...
That's all I have to do? Or has more thing?

Can anyone tell me E-X-A-C-T-L-Y what I have to do to install the mod on version 1.7.10 of Minecraft, please?

Note: I already have the latest version of Forge installed.

**Comment by DarkGuardsman** [comment]
http://www.builtbroken.com/pages/icbm/1.7/

Install instructions are on that page. Too summarize them just add Voltz Engine and ICBM to your mods folder. Make sure both are updated and both are found the same release branch. This means if your using an alpha build for ICBM use the alpha build of voltz engine as well.

Other than that if you getting a crash when launching we will need the crash log. Also make sure your not using the developer.jar.

**Comment by Atum262** [comment]
ICBM-1.7.10-2.3.0b53-dev.jar
VoltzEngine-1.7.10-0.1.0b66-dev

I put these two files in my mods folder and it's ready?

**Comment by Hennamann** [comment]
It should be. if it crashes then supply us with the crash report.

**Comment by Atum262** [comment]
It doesn't crashes, in the game, the launcher is pink and square, and some missiles are missing

**Comment by Hennamann** [comment]
This is because the mod is in alpha, and is being rewritten from scratch, and all the textures and models are not finished, thus leading to the pink and black textures you are seeing.

**Comment by Atum262** [comment]
So I can't use the mod on my minecraft 1.7.10 yet? I have to wait until it be ready?

**Comment by Hennamann** [comment]
You can use it on 1.7.10, but certain features are still being worked on. i would recommend you to be patient. things are being added and fixed all the time.

**Comment by Atum262** [comment]
OK, thank you.
