### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LucidTheStick** [BuiltBrokenModding/ICBM#72]
Can't seem to find a working version.  I took the Crackpack Modpack and attempted to add ICBM.  It looks like it's when ForgeMicroBlocks tries to register ICBM blocks.
ICBM: 2.3.0-63
Voltz: 0.1.0-72
Forge: 1.7.10-10.13.2.1277 & 1.7.10-10.13.2.1230
http://pastebin.com/ciJHB8GK

**Comment by dmodoomsirius** [comment]
I will look into this shortly.

**Comment by LucidTheStick** [comment]
I just saw https://github.com/BuiltBrokenModding/ICBM/issues/57 which seems to be the same thing.

**Comment by Hennamann** [comment]
I experienced this bug myself earlier, it seems to be a problem with the newer versions of voltz/resonant engines itemhandler class... It works fine in singleplayer.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/issues/57
