### ISSUE TITLE
is there something really wrong? or have I not installed correctly?

### ISSUE THREAD

**Issue by txtspeak** [BuiltBrokenModding/ICBM#74]
the only items I have are the missiles of varying sizes with a warhead of tnt or let it snow and a void thruster
and also the portable rocket launcher.
is there supposed to be more stuff? have I installed it incorrectly?
plz help

**Comment by Hennamann** [comment]
You have installed it correctly, the mod is currently being remade from scratch, meaning that most of the stuff from ICBM 1.6.4 is being recreated. most of the content currently missing will be added in the future!

**Comment by txtspeak** [comment]
so... its still not finished by a long way... I was told there was slightly more in it.

**Comment by ipatrol** [comment]
Are you sure? I had this same issue, where only a few missiles and rockets with certain warheads were available. I looked at you wiki, and most of the things that it said were already in the latest version were missing including the warheads and thrusters, and most of the textures apparently.

**Comment by Hennamann** [comment]
If you look at the source code, you'l see everything that is implemented so far, our wiki clearly states that it's WIP(Work in Progress) as such somethings mentioned on the wiki may not be implemented/properly implemented as of yet

**Comment by DarkGuardsman** [comment]
Better question is which wiki are you looking at. As this is the official wiki for ICBM http://www.builtbroken.com/pages/icbm/wiki/ which is not even completed or up to date.

**Comment by Hennamann** [comment]
That was the one i was referring to, but now that you mention it, the documentation for 1.6.4 is all over the place...
