### ISSUE TITLE
Game fails to start with ICBM 1.7.10

### ISSUE THREAD

**Issue by gozulio** [BuiltBrokenModding/ICBM#75]
Log: http://pastebin.com/a1t9vKsd

ICBM version: 2.3.0b80-dev
Voltz Engine version: 0.0.0b50-dev
Forge version: 10.13.2.1291

Issue tested on a blank Forge 1.7.10 instance.

**Comment by Hennamann** [comment]
OK, from what i can see, there's a missing class. 
Could you download the latest version of Voltz engine here: http://www.builtbroken.com/pages/voltzengine/1.7/downloads.php 
And ICBM here: http://www.builtbroken.com/pages/icbm/1.7/downloads.php ?

Also you are running this without any other mods right? If you are running other mods, what mods are you running?

**Comment by gozulio** [comment]
voltz engine was out of date (waaaaay out of date). the version i had came off curseforge and was the most up to date according to there. thank you for the link with the voltz engine download, not sure if i would have found it otherwise =P

**Comment by dmodoomsirius** [comment]
only Released builds for both will go on curseForge otherwise they will be there
