### ISSUE TITLE
mod pack permission

### ISSUE THREAD

**Issue by mrgreaper** [BuiltBrokenModding/ICBM#77]
Hi i did try to email as per the license but it got bounced pack as deliverable.

the original email :
Hi always loved icbm mod and would love to add it to the pack im running on the feed the beast launcher (possibly disabled by default as its in early alpha) 

just seeking permission to do so :)

my mod pack : http://forum.feed-the-beast.com/threads/1-7-10-craft-modpack-tech-magic-casual-server-files.58507/

thanks in advance

Mr D Eastwick (aka mrgreaper)

***************************************************
hope you will forgive the slightly wierd method of using github but couldnt think how else to request permission :)

**Comment by DarkGuardsman** [comment]
https://docs.google.com/spreadsheets/d/13SXh1AeaJx07Tt4MXCg-Kz5mNxXLI-ilShrIZlSC8E8/edit?usp=sharing

You have permission so as long as you wait for it to come out of alpha. Its too buggy right now to be used beyond show boating.

**Comment by mrgreaper** [comment]
Thank you, yeah no problem on waiting. will keep an eye out for the beta (will be using it on my personal test server so will be keeping uptodate anyway, very good to see it being worked on guys )
