### ISSUE TITLE
1.7.10 Version Requires Resonant Engine?

### ISSUE THREAD

**Issue by TSenter** [BuiltBrokenModding/ICBM#78]
I am trying to create a modpack, and I'm using the 1.710 version (which is only supposed to require the Voltz Engine, which I have added), but the console is saying that the Resonant Engine is required. 
> [B#265]  [17:27:46] [Client thread/ERROR]: The mod ICBM (ICBM) requires mods [ResonantEngine] > to be available

I have attempted to add ResonantEngine, but that causes other errors.

**Comment by Hennamann** [comment]
What version og ICBM are you using?

**Comment by dmodoomsirius** [comment]
what version of ICBM and Resonant Engine Are you using?

**Comment by TSenter** [comment]
ICBM-1.4.2.386 and resonant-engine-3.3.0.437-core are the two files I'm using.

**Comment by TSenter** [comment]
I just looked around a little. Is that ICBM for 1.6.4?

**Comment by dmodoomsirius** [comment]
no 1.7.10

**Comment by DarkGuardsman** [comment]
ICBM-1.4.2.386 is 1.6.4 MC and not even listed on our site. Version 2.0.0+ is 1.7.10 and the only version set we support right now. 

http://www.builtbroken.com/pages/icbm/1.7/downloads.php

**Comment by TSenter** [comment]
That fixed it. Thanks!
