### ISSUE TITLE
ICBM - mod split

### ISSUE THREAD

**Issue by excelcrafter** [BuiltBrokenModding/ICBM#82]
Hello,

I like ICBM mod, but...
I will be more happy if ICBM mod is split into:

- turrets
-rocket systems
-explosives

ICBM has the best turrets I have found in 1.6.4 and 1.7.10 aswell, but many of my friends dont want missiles. We were using ICBM only for defense against mobs, not nuking ppl bases.

Another thing, it will be nice if you have option in config to disable laser turrets or gun turrets. If you disable laser turrets, you need some effort to make ammo for gun turrets. Laser turrets will shoot forever, till you have energy, or make laser turrets very hugry after energy, so basically every shot will hurt your energy system.

sincerely ICBM player

**Comment by Hennamann** [comment]
This is currently the plan, decor is being worked on in militarybasedecor, and defenses is worked on in a seperate traps mod. turrets will also be readded in another mod. icbm will now only focus on icbms and similar.

**Comment by excelcrafter** [comment]
I will really like ICBM turrets in separate mod, I luuuuv sound of that turrets shooting everything what moves outside :-D

**Comment by excelcrafter** [comment]
was closed before I finished my message, haha

**Comment by Hennamann** [comment]
You can still post comments when it's closed. it just signifies that the problem/suggestion is solved.
