### ISSUE TITLE
ICBM - minecart mobile gunturret

### ISSUE THREAD

**Issue by excelcrafter** [BuiltBrokenModding/ICBM#83]
Hello again,

I know its probably insane idea, but gunturret on an armored minecart could be very funny I think :-D

Transporting your precious fuel for your electricity generators can be fun again...

I know, I know... Tesseracts, transceivers...bla bla bla

**Comment by Hennamann** [comment]
I like the sound of a armored minecart, and gunturret in a minecart idea isn't too far fetched. But would probably require railcraft for power/electricity...

**Comment by shobu9** [comment]
Railcraft already has that it supports rf .

**Comment by DarkGuardsman** [comment]
Its planned but not in ICBM

**Comment by excelcrafter** [comment]
railcraft has electric loco to pull carts :-)
