### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Omuck3** [BuiltBrokenModding/ICBM#84]
Hi.  I would like to use ICBM in my modpack, the Modded Civilization Pack.  It is focused on realism and modern technology/warfare.  Any other information required?

**Comment by dmodoomsirius** [comment]
What launcher it will be on. Link to pack if there is one. What mods are in the pack?

**Comment by Omuck3** [comment]
It's on the technic launcher.http://www.technicpack.net/modpack/modded-civre-re-posted.595810
The mod list there is out of date.  I've recently added power converters, mekanism, galacticraft, railcraft, better storage, and microblocks.

**Comment by DarkGuardsman** [comment]
Tell me what sets your modpack apart from other warfare packs

**Comment by Omuck3** [comment]
First of all, it's realistic.  There is random spawn and localized chat.
We don't just have warfare, we have a clothing mod, a music mod, food mods,
etc..  As far as I know, it is one of 2 modded servers with a focus on
realism.

**Comment by DarkGuardsman** [comment]
I guess i can give you permission to include ICBM. You just need to wait until i comes out of alpha. As its too buggy for modpack use right now

**Comment by Omuck3** [comment]
Ok, cool!  It's in alpha?  I thought it was all set up.  Any idea when it
will come out of alpha?

**Comment by Hennamann** [comment]
We have no actual estimated time for release, but considering our progress so far, i'd say a good couple of months. don't quote me on that as things could drastically change!

**Comment by DarkGuardsman** [comment]
Actually if all goes well and my collage work load lets off maybe the end of march. As it looks like i'm getting close to start on the missile crafting. Which is the main reason it is still in alpha. As i don't want to release with just small missile and classic recipes. Instead i want to get the missile crafting table working. That way users can customize the missiles and craft them a little more legit.
