### ISSUE TITLE
Server crash on latest build

### ISSUE THREAD

**Issue by mwardrop** [BuiltBrokenModding/ICBM#85]
Added ICBM to direworlf20 mod pack, getting the following crash with Voltz0.3.2-195 and ICBM2.4.0-175

-------------------------------------------------------------------------------------------------------------
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/2/15 11:19 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: li/cil/oc/api/driver/Converter
                at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
                at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
                at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
                at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
                at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
                at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
                at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/driver/Converter
                at java.lang.Class.getDeclaredConstructors0(Native Method)
                at java.lang.Class.privateGetDeclaredConstructors(Class.java:2532)
                at java.lang.Class.getConstructor0(Class.java:2842)
                at java.lang.Class.newInstance(Class.java:345)
                at com.builtbroken.mc.lib.mod.loadable.LoadableHandler.applyModule(LoadableHandler.java:49)
                at com.builtbroken.mc.lib.mod.loadable.LoadableHandler.applyModule(LoadableHandler.java:29)
                at com.builtbroken.mc.core.Engine.preInit(Engine.java:137)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
                at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
                at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
                at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
                ... 5 more
Caused by: java.lang.ClassNotFoundException: li.cil.oc.api.driver.Converter
                at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
                ... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
                Minecraft Version: 1.7.10
                Operating System: Linux (amd64) version 2.6.32-431.29.2.el6.x86_64
                Java Version: 1.7.0_65, Oracle Corporation
                Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
                Memory: 306920712 bytes (292 MB) / 866279424 bytes (826 MB) up to 6355222528 bytes (6060 MB)
                JVM Flags: 4 total; -Xmx6144M -Xms128M -XX:MaxPermSize=256M -XX:+UseConcMarkSweepGC
                AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
                IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
                FML: MCP v9.05 FML v7.10.85.1272 Minecraft Forge 10.13.2.1272 145 mods loaded, 145 mods active
                mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                FML{7.10.85.1272} [Forge Mod Loader] (custom_server.jar) Unloaded->Constructed->Pre-initialized
                Forge{10.13.2.1272} [Minecraft Forge] (custom_server.jar) Unloaded->Constructed->Pre-initialized
                appliedenergistics2-core{rv2-beta-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized
                CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                NotEnoughItems{1.0.3.73} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.73-universal.jar) Unloaded->Constructed->Pre-initialized
                ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
                debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
                act{0.0.2a_1.7.10} [AdminCommandsToolbox] (AdminCommandsToolbox-0.0.2a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
                appliedenergistics2{rv2-beta-1} [Applied Energistics 2] (appliedenergistics2-rv2-beta-1.jar) Unloaded->Constructed->Pre-initialized
                Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized
                CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized
                BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
                Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
                Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
                BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized
                IC2{2.2.648-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.648-experimental.jar) Unloaded->Constructed->Pre-initialized
                Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized
                bcapiHolder{1.0} [bcapiHolder] (bcapi-6.0.x.jar) Unloaded->Constructed->Pre-initialized
                BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
                BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized
                BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized
                BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized
                ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized
                ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized
                BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) Unloaded->Constructed->Pre-initialized
                BinnieCore{2.0-dev5} [Binnie Core] (binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
                ExtraTrees{2.0-dev5} [Extra Trees] (binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
                binnie-fix-dev5{1.0} [BinnieFixDev5] (binnie-fix-dev5-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized
                Botany{2.0-dev5} [Botany] (binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
                ExtraBees{2.0-dev5} [Extra Bees] (binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
                Genetics{2.0-dev5} [Genetics] (binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
                AWWayofTime{v1.3.0Beta} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0Beta-6.jar) Unloaded->Constructed->Pre-initialized
                Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
                Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized
                Botania{r1.3-143} [Botania] (Botania r1.3-143.jar) Unloaded->Constructed->Pre-initialized
                BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
                BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
                BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
                BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
                BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized
                CarpentersBlocks{3.2.8} [Carpenter's Blocks] (Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
                ChickenChunks{1.3.4.14} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized
                ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
                chisel{2.1.3} [Chisel] (Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized
                CompactSolars{4.4.37.314} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.37.314-universal.jar) Unloaded->Constructed->Pre-initialized
                ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                EnderIO{1.7.10-2.2.5.311} [Ender IO] (EnderIO-1.7.10-2.2.5.311.jar) Unloaded->Constructed->Pre-initialized
                EnderStorage{1.4.5.26} [EnderStorage] (EnderStorage-1.7.10-1.4.5.26-universal.jar) Unloaded->Constructed->Pre-initialized
                EnderZoo{1.7.10-1.0.7.16} [Ender Zoo] (EnderZoo-1.7.10-1.0.7.16.jar) Unloaded->Constructed->Pre-initialized
                ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized
                factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
                factorization{1.7.10-0.8.88.1} [Factorization] (Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
                factorization.misc{1.7.10-0.8.88.1} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
                FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized
                funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-3.jar) Unloaded->Constructed->Pre-initialized
                HelpFixer{1.0.5} [HelpFixer] (HelpFixer-1.0.5.jar) Unloaded->Constructed->Pre-initialized
                IC2NuclearControl{2.0.5b-Unicorn} [Nuclear Control 2] (IC2NuclearControl-2.0.5b-Unicorn.jar) Unloaded->Constructed->Pre-initialized
                VoltzEngine{0.3.2} [Voltz Engine] (VoltzEngine-1.7.10-0.3.2b195-dev.jar) Unloaded->Constructed->Errored
                icbm{2.4.0.175} [ICBM] (ICBM-1.7.10-2.4.0b175-dev.jar) Unloaded->Constructed->Errored
                iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
                inpure|core{1.7.10R1.0.0B7} [INpureCore] (INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed->Pre-initialized
                inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized
                IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized
                Waila{1.5.6a} [Waila] (Waila-1.5.6a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
                JABBA{1.2.0} [JABBA] (Jabba-1.2.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized
                JourneyMapServer{1.0.2_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.2_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
                LogisticsPipes{0.8.2.86} [Logistics Pipes] (logisticspipes-0.8.2.86.jar) Unloaded->Constructed->Pre-initialized
                Timber{1.0} [Timber] (Lumberjack-1.7.10-1.0.0.2.jar) Unloaded->Constructed->Pre-initialized
                Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
                TConstruct{1.7.10-1.7.1.build803} [Tinkers' Construct] (TConstruct-1.7.10-1.7.1d.jar) Unloaded->Constructed->Pre-initialized
                ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed->Pre-initialized
                MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
                RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized
                Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
                MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
                MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized
                ProjRed|Core{4.5.6.57} [ProjectRed] (ProjectRed-1.7.10-4.5.6.57-Base.jar) Unloaded->Constructed->Pre-initialized
                ProjRed|Exploration{4.5.6.57} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.6.57-World.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                TwilightForest{2.3.1} [The Twilight Forest] (twilightforest-1.7.10-2.3.1.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized
                MineMenu{1.1.8} [MineMenu] (MineMenu-1.7.10-1.1.8.B40-universal.jar) Unloaded->Constructed->Pre-initialized
                MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9B.jar) Unloaded->Constructed->Pre-initialized
                numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) Unloaded->Constructed->Pre-initialized
                powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.176.jar) Unloaded->Constructed->Pre-initialized
                Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized
                Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed->Pre-initialized
                NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
                NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
                NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
                NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
                NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
                neiintegration{1.0.3} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
                ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
                OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized
                OpenPeripheralCore{0.5.0} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-0.5.0-snapshot-172.jar) Unloaded->Constructed->Pre-initialized
                OpenPeripheral{0.2.0} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.2.0-snapshot-139.jar) Unloaded->Constructed->Pre-initialized
                OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed->Pre-initialized
                OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-17.jar) Unloaded->Constructed->Pre-initialized
                PneumaticCraft{1.4.3-40} [PneumaticCraft] (PneumaticCraft-1.7.10-1.4.3-40-universal.jar) Unloaded->Constructed->Pre-initialized
                ProjRed|Transmission{4.5.6.57} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.6.57-Integration.jar) Unloaded->Constructed->Pre-initialized
                ProjRed|Compatibility{4.5.6.57} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.6.57-Compat.jar) Unloaded->Constructed->Pre-initialized
                ProjRed|Integration{4.5.6.57} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.6.57-Integration.jar) Unloaded->Constructed->Pre-initialized
                ProjRed|Illumination{4.5.6.57} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.6.57-Lighting.jar) Unloaded->Constructed->Pre-initialized
                StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized
                StevesFactoryManager{A92} [Steve's Factory Manager] (StevesFactoryManagerA92.jar) Unloaded->Constructed->Pre-initialized
                ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-29.jar) Unloaded->Constructed->Pre-initialized
                TiCTooltips{1.1.11b} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized
                TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized
                Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized
                WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
                witchery{0.20.6} [Witchery] (witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized
                WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
                WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
                WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
                McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
                aobd{2.3.5} [Another One Bites The Dust] (AOBD-2.3.5.jar) Unloaded->Constructed->Pre-initialized
                denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
                ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
                OpenModsLib crash transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
                AE2 Version: beta rv2-beta-1 for Forge 10.13.2.1230
                Mantle Environment: Environment healthy.
                TConstruct Environment: Environment healthy.
                Profiler Position: N/A (disabled)
                Is Modded: Definitely; Server brand changed to 'fml,forge'
                Type: Dedicated Server (map_server.txt)

**Comment by Hennamann** [comment]
This is probably caused by another mod, it seems like voltz engine/icbm modifies a class another mod uses... I'l look into what mods are included in direwolf 20 1.7.10

**Comment by DarkGuardsman** [comment]
@Hennamann this is our fault. I was toying around with Open Computer support and looks like the proxy didn't fire correctly.

**Comment by DarkGuardsman** [comment]
I think this is solved, if not feel free to re-open the issue
