### ISSUE TITLE
Server-side NoClassDefFoundError

### ISSUE THREAD

**Issue by ChatFawkes** [BuiltBrokenModding/ICBM#86]
ICBM Version: ICBM-1.7.10-2.4.0b175-dev
[Crash Report](https://gist.github.com/ChatFawkes/78ca7e66fa9bcec6336b)

Happens when trying to load a Forge 1291 server with ICBM.

**Comment by DarkGuardsman** [comment]
Its due to me trying to make the interface client side only. I'll work on some kind of solution.
