### ISSUE TITLE
Port to nova

### ISSUE THREAD

**Issue by louisw22** [BuiltBrokenModding/ICBM#87]
I know you hate calclavia darkguardsman, however he has teamed up with others modders to create a system to make updating your minecraft mods less intensive.

http://www.novaapi.net/

**Comment by DarkGuardsman** [comment]
lol i don't hate calclavia i just don't like working with him. Which is not the reason why i don't want to use nova. It is a nice idea but no different than voltz engine or resonant engine. Both were designed to make updating less intensive. As well with 20 mods on my work table i prefer to use my own engine.

**Comment by louisw22** [comment]
@DarkGuardsman Why have you made so many mods recently, you seem to start on a mod, never finish it and then create a new one. At this rate, will it be possible for you to maintain them all? In my opinion ICBM and Voltz Engine should be you focus as ICBM is currently nowhere as complete as it used to be.

**Comment by dmodoomsirius** [comment]
@louisw22 Dark works on many mods at once. We are testing them on the Voltz beta server.

**Comment by Parker8283** [comment]
Nova is NOT a replacement for Forge. Nova is like Bukkit and Sponge, an abstraction layer. Therefore, it'd be like the old days of everyone wanting mods porting to Bukkit. Some people prefer interfacing directly with Minecraft. Some prefer the abstraction layer. Preference of the mod maker.

Also, yea, Dark does have lots of mods, and sadly, not infinite time. So that kind of thing will happen. Also, if you're going to dictate what should be a high priority and talk about how incomplete things are, how about helping out? Otherwise, let the team work.

**Comment by DarkGuardsman** [comment]
Right now i only release two mods voltz engine and ICBM. The rest are work in progress projects for content i wish to make. For example 'addicted to red' i just added 4 detectors and a chat block. FarmTech i created for the sole purpose of making an easy chicken farm. It hurts to die is designed to make death more interesting. Like losing items depending on the conditions of death

**Comment by louisw22** [comment]
@Parker8283 I know what nova is and what is does, i was just suggesting it so @DarkGuardsman could easily update his hard work to 1.8 as it is going to be a huge update. 
@DarkGuardsman Well done for the Mad science port, how well does it run?

**Comment by DarkGuardsman** [comment]
The trick is it would take 10 to 20 times more work to port to nova than to 1.8 directly. Plus nova doesn't support even half of the things I need to do. Thank you to for the suggestion anyways.

As for madscience i did an init update. Currently i've only updated the clay furnace and most of the items. I have to rewrite 80% of it from scratch as it was not coded with maintenance in mind. Luckily the author is ok with me doing what ever i want.
