### ISSUE TITLE
Reinforced Concrete

### ISSUE THREAD

**Issue by Tomson124** [BuiltBrokenModding/ICBM#92]
Will the Concrete blocks and its different tiers readded to ICBM or will they be in an other mod?
Would really like to have them back for a wither farm or a nuclear bunker :D

**Comment by Hennamann** [comment]
They are being remade in a WIP mod called military base decor.  If you need something as a replacement you could check out my mod personal mod project (not builtbroken): Blastcraft located here: http://www.curse.com/mc-mods/minecraft/224916-blastcraft
