### ISSUE TITLE
Ticking Block Entity crash when launching a missile

### ISSUE THREAD

**Issue by ajthemacboy** [BuiltBrokenModding/ICBM#96]
Report: http://pastebin.com/1qErU2VT

Latest versions of both ICBM and VoltzEngine. 

Also, the missile station has a missing texture, the Launch Controller just says "container.inventory.basic.name, gui.icbm:controller.links.none", and there are only small missiles.

Is the mod just in a very early stage, or is there something wrong with me?

I'm using Forge 1395. The crash report is from a Cauldron server, 1383 if I remember correctly, but the crash also happens in singleplayer.

Thanks!

**Comment by Hennamann** [comment]
The mod is still in development, so missing textures, and unlocalized names are normal. As for your error: It's either your ICBM jar file being corrupted(errored during download) or cauldron messing it up, I would recommend recreating the error again, without cauldron, and post the crash report again if it crashes without cauldron aswell. If this is an error with ICBM and not cauldron, @DarkGuardsman can probably look at it.

**Comment by DarkGuardsman** [comment]
Should have already been fix in the last dev copy. Check the web site instead of curse for downloads

**Comment by ajthemacboy** [comment]
As I said, I have the latest version from the website and it happens in singleplayer as well. As for still being in development, I completey understand.

**Comment by DarkGuardsman** [comment]
hmm your a version behind but still using close enough to the latest. Its odd that this issue was not fixed in that version. As it was confirmed to be fixed in this issue https://github.com/BuiltBrokenModding/ICBM/issues/94


Notes:
func_70016_h,setVelocity,0,"Sets the velocity to the args. Args: x, y, z"
