### ISSUE TITLE
Portable Launcher crash when firing a missile

### ISSUE THREAD

**Issue by jobensingh** [BuiltBrokenModding/ICBM#98]
Hi, I noticed, well more than just noticed, that whenever i launch a missile out of a portable launcher the missile just fly's up and keeps going up until eventually my server crashes. Just reporting this bug and hope it could get fixed soon

**Comment by Hennamann** [comment]
The portable launcher is mainly for developer testing. I would recommend using the small silo and the launch controllers to launch missiles with proper coordinates. I'm closing this since it's not really a problem, But if there's anything else feel free to comment.

**Comment by DarkGuardsman** [comment]
@Hennamann its actually no longer just a dev tool and can be used as a normal launcher. 

@jobensingh Going to need that crash log and the version you are using.

**Comment by Hennamann** [comment]
@DarkGuardsman Ah sorry my mistake.

**Comment by jobensingh** [comment]
Hi Sorry I didnt reply earlier I couldnt find this page but here is the crash report, Also Im pretty sure this is the correct crash report but I have a lot so im not 100% if this the right one, if its not let me know.
http://pastebin.com/2dbBZjGh

**Comment by jobensingh** [comment]
Also with the silo I cant find anywhere to input the coordinates

**Comment by Hennamann** [comment]
There should be block called: "Launcher controller" place that next to a silo and right click it and you can enter coordinated and fire missiles.

**Comment by jobensingh** [comment]
I tried that, but whenever i right click the launcher control it gives me this screen
![2015-06-06_15 29 31](https://cloud.githubusercontent.com/assets/12707917/8021731/d025cf78-0c60-11e5-928f-544918a8d134.png)

**Comment by DarkGuardsman** [comment]
The place next to auto linking is not coded yet. Instead you use the linking tool to connect up to 5 launchers to a single controller. Sneak-right click to save the link and right click to input it into the controller. You can also use the GPS flag to set the launching coords on the silo directly.

**Comment by jobensingh** [comment]
When I try to use the launcher to input coords it just gives me a blank screen that has an update button
![2015-06-07_13 53 51](https://cloud.githubusercontent.com/assets/12707917/8026063/40ea882c-0d1d-11e5-9de8-a6fa302d4f25.png)
and when I try to input the coords to the silo directly I can get the gps flag to turn green but when i right click a silo it goes to red without saying any information and why i try to launch the game crashes after a little while as usual.

**Comment by jobensingh** [comment]
All this leads to my original problem which was in the Title
